// Original introductory exercises. These are not copied Chess.com lessons.
const start = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
export const lessons = [
 {id:'safe-king',title:'Your king comes first',category:'Fundamentals',description:'Recognize check and choose a legal escape.',fen:'4k3/8/8/8/8/8/4r3/4K3 w - - 0 1',body:['Check means an opposing piece attacks your king. Your next move must remove that attack.','You can move the king, capture the checking piece if it is safe, or block a line attack. A king cannot remain in check.','Here, the black rook checks the white king along the e-file. The unprotected rook on e2 can be captured by the king.'],question:'Which move removes the check in this position?',choices:['Kxe2, capturing the rook','Stay on e1 and pass','Move a pawn that is not on the board'],answer:0,explanation:'Kxe2 captures the checking rook. The black king on e8 does not attack e2.'},
 {id:'center',title:'Give your pieces room',category:'Openings',description:'Use a central pawn to open paths for development.',fen:start,body:['At the start, pawns block most of your bishops and your queen. A central pawn move can open useful paths.','After e4, the bishop on f1 can develop along its diagonal. You also influence d5 and f5.','A good opening habit is to bring pieces into the game and prepare king safety. There is no single compulsory first move.'],question:'What does 1. e4 immediately make possible?',choices:['Castling immediately','The f1 bishop can leave its starting square','Capturing the black queen'],answer:1,explanation:'Moving the e-pawn opens the f1 bishop’s diagonal. Castling still requires other pieces to move and safe king squares.'},
 {id:'whole-exchange',title:'Count the whole exchange',category:'Tactics',description:'Compare material after the recapture.',fen:'4k3/8/8/8/4r3/3P4/8/4K3 w - - 0 1',body:['A piece’s value is a rough guide, not a complete position evaluation. Typical values are pawn 1, knight 3, bishop 3, rook 5 and queen 9.','Count all captures and recaptures before comparing choices. Losing a rook and taking a bishop costs about two material points, not five.','Here the pawn on d3 can take the unprotected rook on e4. Ask what the opponent can do next before assuming a longer line is forced.'],question:'A rook is lost and a bishop is captured in return. What is the approximate material cost?',choices:['5 points','8 points','2 points'],answer:2,explanation:'Using the conventional values, 5 minus 3 is 2. Position, activity and king safety can change the practical evaluation.'},
 {id:'king-safety',title:'Make room to castle',category:'Openings',description:'Understand the conditions for castling.',fen:'r3k2r/pppp1ppp/2n1bn2/4p3/4P3/2N1BN2/PPPP1PPP/R3K2R w KQkq - 0 1',body:['Castling moves the king two squares toward a rook, and that rook goes to the square the king crossed.','The king and participating rook must not have moved. The squares between them must be empty.','You cannot castle while in check, through an attacked square, or into check. A rook being attacked does not itself prevent castling.'],question:'Which condition prevents castling?',choices:['The rook is attacked','The king would cross an attacked square','The opponent still has a queen'],answer:1,explanation:'The king’s current, transit and destination squares must be safe. The rook’s square does not have the same restriction.'},
 {id:'checkmate',title:'Check is not checkmate',category:'Endgames',description:'Look for every legal escape.',fen:'7k/5K2/6Q1/8/8/8/8/8 w - - 0 1',body:['A check is checkmate only when the defending side has no legal reply.','Before declaring mate, check king escapes, possible captures of the attacking piece and possible blocks.','In this position Qg7 delivers mate: the white king protects the queen, and the queen covers the black king’s escape squares.'],question:'What makes a checking move checkmate?',choices:['The king has no legal way to escape the check','The move wins a rook','The checking piece is a queen'],answer:0,explanation:'Checkmate depends on all legal replies, not on the value or type of the checking piece.'},
 {id:'review-habit',title:'Review one decision well',category:'Study habits',description:'Turn an engine line into something you understand.',fen:start,body:['Start with a move you did not understand. Write what you expected the opponent to do.','Play the reply you expected, then examine another legal reply. Notice which piece, threat or exchange changes.','An engine’s preferred continuation is evidence at a search limit. Your learning task is to explain the important consequence and recognize it in another position.'],question:'Which review habit tests your understanding?',choices:['Memorize the score without playing any moves','Assume the opponent must follow one displayed line','Predict a reply, test it and explain the consequence'],answer:2,explanation:'A prediction gives you something to check. Comparing alternatives helps distinguish an example line from a forced result.'}
];
export const puzzles = [
 {id:'take-the-rook',title:'A rook left loose',theme:'Free pieces',fen:'4k3/8/8/8/4r3/3P4/8/4K3 w - - 0 1',side:'w',hint:'A pawn captures diagonally. Look at d3.',solution:['d3e4'],explanation:'dxe4 takes the unprotected rook with a pawn.'},
 {id:'queen-mate',title:'Close the escape squares',theme:'Mate in one',fen:'7k/5K2/6Q1/8/8/8/8/8 w - - 0 1',side:'w',hint:'Your king protects g7.',solution:['g6g7'],explanation:'Qg7 is checkmate. The king on f7 protects g7, and the queen covers the black king’s escapes.'},
 {id:'back-rank',title:'The crowded back rank',theme:'Mate in one',fen:'6k1/5ppp/8/8/8/8/8/4R1K1 w - - 0 1',side:'w',hint:'The black king’s own pawns block its escape.',solution:['e1e8'],explanation:'Re8 is checkmate: the rook checks along the eighth rank and the black pawns deny the king flight squares.'},
 {id:'black-back-rank',title:'See it from Black’s side',theme:'Mate in one',fen:'4r1k1/8/8/8/8/8/5PPP/6K1 b - - 0 1',side:'b',hint:'Look for a rook move to the first rank.',solution:['e8e1'],explanation:'Re1 is checkmate. The white pawns block the king’s escape squares.'},
 {id:'knight-fork',title:'Check and a second target',theme:'Knight fork',fen:'6k1/8/8/3q1N2/8/8/8/6K1 w - - 0 1',side:'w',hint:'Find a knight check that also attacks the queen on d5.',solution:['f5e7','g8f7','e7d5'],explanation:'Ne7 checks the king and attacks d5. After the demonstrated king reply, Nxd5 wins the queen. Other king replies are possible; this exercise follows one legal line.'},
 {id:'promote',title:'Finish the pawn’s journey',theme:'Promotion',fen:'7k/P7/6K1/8/8/8/8/8 w - - 0 1',side:'w',hint:'Move the a-pawn forward and choose a queen.',solution:['a7a8q'],explanation:'a8=Q promotes the pawn. Promotion is part of the move, so the chosen piece must be recorded.'}
];
export function catalog() {
 return {lessons:lessons.map(({answer,explanation,...lesson})=>lesson),puzzles:puzzles.map(({solution,explanation,...puzzle})=>puzzle)};
}
