/* Run after `npm run build`; uses a fresh database and the real server engine. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { randomBytes } = require('node:crypto');
const { Chess } = require('chess.js');
const { pathToFileURL } = require('node:url');
const express = require('express');
const root = path.resolve(__dirname, '..');
const packageRoot = process.env.CHESSLAB_PLAYWRIGHT_ROOT || 'playwright';
const { chromium } = require(packageRoot);
const evidence = process.env.CHESSLAB_EVIDENCE_DIR && path.resolve(process.env.CHESSLAB_EVIDENCE_DIR);
if (evidence) fs.mkdirSync(evidence, {recursive:true});

(async () => {
  const dist = path.join(root, 'web/dist');
  assert.ok(fs.existsSync(path.join(dist, 'index.html')), 'Build the application first with npm run build.');
  const { createApp } = await import(pathToFileURL(path.join(root, 'server/app.mjs')));
  const engine = await import(pathToFileURL(path.join(root, 'server/engine.mjs')));
  const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'chesslab-browser-'));
  let state, server, browser;
  try {
    state = createApp({ databasePath: path.join(temporary, 'chesslab.sqlite') });
    state.app.use(express.static(dist));
    server = state.app.listen(0, '127.0.0.1');
    await new Promise((resolve, reject) => { server.once('listening', resolve); server.once('error', reject); });
    const base = `http://127.0.0.1:${server.address().port}`;
    browser = await chromium.launch({ headless: true, ...(evidence?{slowMo:120}:{}) });
    const context = await browser.newContext({ viewport: { width: 1440, height: 960 }, reducedMotion: 'reduce', ...(evidence?{recordVideo:{dir:evidence,size:{width:1440,height:960}}}:{}) });
    const page = await context.newPage();
    page.setDefaultTimeout(20000);
    const pageErrors = [], badResponses = [], unexpectedRequests = [];
    page.on('pageerror', error => pageErrors.push(error.message));
    page.on('response', response => { if (response.status() >= 400) badResponses.push(`${response.status()} ${new URL(response.url()).pathname}`); });
    page.on('request', request => {
      const url = new URL(request.url());
      if (url.protocol.startsWith('http') && (url.origin !== base || /\.(wasm|nnue|onnx|pt|pb)(\.|$)/i.test(url.pathname))) unexpectedRequests.push(request.url());
    });
    const responseFor = (route, method = 'POST') => page.waitForResponse(response => new URL(response.url()).pathname === route && response.request().method() === method);
    async function actionResponse(route, action, status = 200) {
      const [response] = await Promise.all([responseFor(route), action()]);
      assert.equal(response.status(), status, route);
      return response.json();
    }
    const navigation = page.getByRole('navigation', { name: 'Main navigation' });
    const entry = page.getByLabel('Enter a move in SAN or UCI', { exact: true });
    async function enterMove(value) {
      await entry.fill(value);
      await page.getByRole('button', { name: 'Play entered move', exact: true }).click();
    }

    const botsLoaded = responseFor('/api/bots', 'GET');
    await page.goto(base);
    assert.equal((await botsLoaded).status(),200);
    if(evidence) await page.screenshot({path:path.join(evidence,'01-bot-picker.png'),fullPage:true});
    if(process.env.CHESSLAB_BASELINE_ONLY==='1'){console.log('Baseline screenshot recorded');await context.close();return;}
    await page.waitForFunction(() => [...document.querySelectorAll('.board img.piece')].length === 32 && [...document.querySelectorAll('.board img.piece')].every(image => image.complete && image.naturalWidth === 150));
    assert.equal(new Set(await page.locator('.board img.piece').evaluateAll(images => images.map(image => new URL(image.src).pathname))).size, 12, 'All twelve piece images load on the starting board');
    await page.setViewportSize({width:1280,height:720});
    assert.ok(await page.locator('.move-entry').evaluate(element=>element.getBoundingClientRect().bottom<=innerHeight),'Laptop move entry stays above the fold');
    assert.ok(await page.locator('.start-button').evaluate(element=>element.getBoundingClientRect().bottom<=innerHeight),'Laptop start button stays above the fold');
    if(evidence) await page.screenshot({path:path.join(evidence,'00-laptop-picker.png'),fullPage:true});
    await page.setViewportSize({width:1440,height:960});
    await page.getByRole('button',{name:'Set up position',exact:true}).click();
    const guestEditor=page.getByRole('dialog',{name:'Set up position',exact:true}),guestFen='4k3/8/8/8/8/8/8/4K2R b - - 0 9';
    await guestEditor.getByLabel('Load FEN',{exact:true}).fill(guestFen);await guestEditor.getByRole('button',{name:'Load position',exact:true}).click();
    await guestEditor.getByLabel('Study title',{exact:true}).fill('Guest draft');await guestEditor.getByRole('button',{name:'Save & analyze position',exact:true}).click();
    await page.getByRole('dialog',{name:'Make this your workspace',exact:true}).getByRole('button',{name:'Close dialog',exact:true}).click();
    assert.equal(await guestEditor.getByLabel('Current FEN',{exact:true}).inputValue(),guestFen);assert.equal(await guestEditor.getByLabel('Study title',{exact:true}).inputValue(),'Guest draft');
    await guestEditor.getByRole('button',{name:'Close dialog',exact:true}).click();
    const search = page.getByRole('searchbox', {name:'Search bots'});
    await search.fill('no_such_chess_opponent');
    await page.getByText('No opponents found', {exact:true}).waitFor();
    await page.getByRole('button', {name:'Clear search',exact:true}).click();
    await search.fill('Martin');
    assert.equal(await page.locator('.bot-card').count(),1,'Search finds the named opponent');
    assert.match(await page.locator('.bot-card').innerText(),/Martin/,'Bot name is visible');
    await page.locator('.account-button').click();
    const dialog = page.getByRole('dialog', { name: 'Make this your workspace' });
    await dialog.getByLabel('Username', { exact: true }).fill('browser_smoke');
    await dialog.getByLabel('Password', { exact: true }).fill(randomBytes(24).toString('hex'));
    const account = await actionResponse('/api/register', () => dialog.getByRole('button', { name: 'Create account', exact: true }).click(), 201);
    assert.equal(account.user.username, 'browser_smoke');
    await dialog.waitFor({ state: 'hidden' });
    const cookie = (await context.cookies(base)).find(item => item.name === 'chesslab_session');
    assert.ok(cookie?.httpOnly && cookie.sameSite === 'Strict', 'Session must be HttpOnly and SameSite=Strict.');

    await page.getByRole('searchbox', {name:'Search bots'}).fill('Martin');
    await page.getByRole('button', { name: 'Play Martin, 250', exact: true }).click();
    const created = await actionResponse('/api/games', () => page.locator('.welcome-panel').getByRole('button', { name: 'Play Martin', exact: true }).click(), 201);
    const gameRoute = `/api/games/${created.game.id}`;
    const humanResponse = responseFor(`${gameRoute}/move`);
    const replied = await actionResponse(`${gameRoute}/bot`, () => enterMove('e4'));
    const human = await humanResponse;
    assert.equal(human.status(), 200);
    assert.deepEqual((await human.json()).game.moves, ['e2e4']);
    assert.equal(replied.game.moves.length, 2);
    assert.equal(replied.game.moves[0], 'e2e4');
    engine.replay(replied.game.moves, replied.game.initialFen);
    await page.getByRole('button', { name: /^Move 1, black,/ }).waitFor();
    await page.getByRole('button', { name: 'e4, white pawn', exact: true }).waitFor();
    if(evidence) await page.screenshot({path:path.join(evidence,'02-local-game.png'),fullPage:true});
    const hint = await actionResponse(`${gameRoute}/hint`,()=>page.getByRole('button',{name:/^Hint /}).click());
    assert.ok(hint.move && hint.explanation, 'Hint contains real engine evidence');
    await page.locator('.hint-message').waitFor();

    const review = await actionResponse('/api/analyze', () => page.locator('.panel-tabs').getByRole('button', { name: /^Review/ }).click());
    assert.match(review.engine, /Stockfish/);
    assert.ok(review.played && review.lines.length);
    await page.locator('.coach-explanation').waitFor();
    assert.match(await page.locator('.engine-receipt').innerText(), /Stockfish/);
    assert.match(await page.locator('.coach-explanation').innerText(), /sample|estimate/i);

    if(evidence) await page.screenshot({path:path.join(evidence,'03-engine-review.png'),fullPage:true});
    await page.getByRole('button',{name:'Try a variation',exact:true}).click();
    await page.getByLabel('Your question at this branch').fill('What changes if I develop my knight?');
    const variationMove = engine.replay(replied.game.moves).moves()[0];
    await enterMove(variationMove);
    await page.getByRole('button',{name:'Branch here',exact:true}).click();
    await page.getByLabel('Your question at this branch').fill('A second branch, inside the first.');
    const study = await actionResponse(`${gameRoute}/study`,()=>page.getByRole('button',{name:'Save study',exact:true}).click());
    assert.equal(study.game.study.branches.length,2);
    assert.equal(study.game.study.branches[1].parentId,study.game.study.branches[0].id);
    assert.deepEqual(study.game.moves,replied.game.moves,'Exploration preserves the actual game');
    if(evidence) await page.screenshot({path:path.join(evidence,'04-nested-study.png'),fullPage:true});
    await page.getByRole('button',{name:'Practice this position',exact:true}).click();
    const practiceDialog=page.getByRole('dialog',{name:'Practice this position',exact:true});
    await practiceDialog.getByRole('searchbox',{name:'Search bots',exact:true}).fill('Martin');
    if(evidence) await page.screenshot({path:path.join(evidence,'12-position-setup.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Practice setup has no mobile overflow');
    if(evidence) await page.screenshot({path:path.join(evidence,'13-mobile-position-setup.png'),fullPage:false});
    await page.setViewportSize({width:1440,height:960});
    const practiced=await actionResponse(`${gameRoute}/practice`,()=>practiceDialog.getByRole('button',{name:'Start position practice',exact:true}).click(),201);
    const practiceRoute=`/api/games/${practiced.game.id}`;
    assert.deepEqual(practiced.game.moves,study.game.study.branches[1].moves,'Practice copies the exact nested branch');
    assert.equal(practiced.game.color,engine.replay(practiced.game.moves,practiced.game.initialFen).turn());
    const localMove=engine.replay(practiced.game.moves,practiced.game.initialFen).moves()[0];
    const practiceReply=responseFor(practiceRoute+'/bot');await enterMove(localMove);
    const playedPractice=(await (await practiceReply).json()).game;
    assert.equal(playedPractice.moves.length,practiced.game.moves.length+2);engine.replay(playedPractice.moves,playedPractice.initialFen);
    if(evidence) await page.screenshot({path:path.join(evidence,'14-native-position-practice.png'),fullPage:true});
    const undoPractice=await actionResponse(practiceRoute+'/undo',()=>page.getByRole('button',{name:/^Undo /}).click());
    assert.deepEqual(undoPractice.game.moves,practiced.game.moves,'Takeback stops at the chosen position');
    const restartedPractice=await actionResponse(practiceRoute+'/practice',()=>page.getByRole('button',{name:'Restart position',exact:true}).click(),201);
    assert.deepEqual(restartedPractice.game.moves,practiced.game.moves);assert.deepEqual(restartedPractice.game.practice,practiced.game.practice);
    const reopenedPractice=responseFor(`/api/games/${restartedPractice.game.id}`,'GET');await page.reload();
    assert.deepEqual((await (await reopenedPractice).json()).game.practice,practiced.game.practice);
    await page.getByRole('button',{name:'Return to source study',exact:true}).click();
    await page.getByLabel('Your question at this branch').waitFor();
    assert.equal(await page.getByLabel('Your question at this branch').inputValue(),'A second branch, inside the first.');
    const unchangedSource=(await (await context.request.get(base+gameRoute)).json()).game;
    assert.deepEqual(unchangedSource.moves,replied.game.moves);assert.deepEqual(unchangedSource.study,study.game.study);
    if(evidence) await page.screenshot({path:path.join(evidence,'15-returned-source-study.png'),fullPage:true});

    await page.getByRole('button',{name:/^Return to game/}).click();
    await actionResponse(`${gameRoute}/study`,()=>page.getByRole('button',{name:'Save study',exact:true}).click());
    const restoredResponse = responseFor(gameRoute, 'GET');
    await page.reload();
    const restored = await restoredResponse;
    assert.equal(restored.status(), 200);
    assert.deepEqual((await restored.json()).game.moves, replied.game.moves);
    await page.getByRole('button', { name: 'Move 1, white, e4', exact: true }).waitFor();
    await page.getByRole('button', { name: /^Move 1, black,/ }).waitFor();

    await navigation.getByRole('button', { name: 'Learn', exact: true }).click();
    await page.getByRole('button', { name: /Your king comes first/ }).click();
    const wrongLesson = await actionResponse('/api/lessons/safe-king/answer', () => page.getByRole('button', { name: /Stay on e1 and pass/ }).click());
    assert.equal(wrongLesson.correct, false);
    assert.deepEqual(wrongLesson.progress.lessons, []);
    await page.locator('.learning-feedback.incorrect').waitFor();
    const rightLesson = await actionResponse('/api/lessons/safe-king/answer', () => page.getByRole('button', { name: /Kxe2, capturing the rook/ }).click());
    assert.equal(rightLesson.correct, true);
    assert.deepEqual(rightLesson.progress.lessons, ['safe-king']);
    await page.locator('.learning-feedback.correct').waitFor();

    await navigation.getByRole('button', { name: 'Puzzles', exact: true }).click();
    await page.getByRole('button',{name:'Starter exercises',exact:true}).click();
    await page.getByRole('button', { name: /A rook left loose/ }).click();
    const wrongPuzzle = await actionResponse('/api/puzzles/take-the-rook/answer', () => enterMove('e1d1'));
    assert.equal(wrongPuzzle.correct, false);
    assert.deepEqual(wrongPuzzle.progress.puzzles, []);
    await page.locator('.learning-feedback.incorrect').waitFor();
    const rightPuzzle = await actionResponse('/api/puzzles/take-the-rook/answer', () => enterMove('d3e4'));
    assert.equal(rightPuzzle.complete, true);
    assert.deepEqual(rightPuzzle.progress.puzzles, ['take-the-rook']);
    await page.locator('.learning-feedback.correct').waitFor();
    assert.match(await page.locator('.learning-feedback.correct').innerText(), /Puzzle complete/);

    if(evidence) await page.screenshot({path:path.join(evidence,'05-puzzle-complete.png'),fullPage:true});
    const meResponse = responseFor('/api/me', 'GET');
    await page.reload();
    const me = await meResponse;
    assert.equal(me.status(), 200);
    assert.deepEqual((await me.json()).progress, { lessons: ['safe-king'], puzzles: ['take-the-rook'] });
    await page.getByRole('button', { name: 'Move 1, white, e4', exact: true }).waitFor();
    await navigation.getByRole('button',{name:'My games',exact:true}).click();
    await page.locator('.game-card').first().waitFor();
    if(evidence) await page.screenshot({path:path.join(evidence,'06-saved-games.png'),fullPage:true});
    await page.getByRole('button',{name:'Open settings',exact:true}).click();
    const settingsDialog=page.getByRole('dialog',{name:'Settings',exact:true});
    await settingsDialog.getByLabel('Board',{exact:true}).selectOption('blue');
    await settingsDialog.getByRole('button',{name:'Close dialog',exact:true}).click();
    await page.reload();
    await page.getByText('Coach online',{exact:true}).waitFor();
    assert.equal(await page.locator('.app-shell').getAttribute('data-board-theme'),'blue','Board preference persists');
    await page.getByRole('button',{name:'Open settings',exact:true}).click();
    await page.getByRole('dialog',{name:'Settings',exact:true}).getByLabel('Board',{exact:true}).selectOption('green');
    await page.getByRole('button',{name:'Close dialog',exact:true}).click();
    await navigation.getByRole('button',{name:'My games',exact:true}).click();
    await page.getByRole('button',{name:'Import a PGN',exact:true}).click();
    await page.getByLabel('PGN text',{exact:true}).fill('[White "Learner"]\n[Black "Practice opponent"]\n\n1. f3 e5 2. g4 Qh4# 0-1');
    const imported=await actionResponse('/api/import',()=>page.getByRole('button',{name:'Import & review',exact:true}).click(),201);
    const reportRoute=`/api/games/${imported.game.id}/review`;
    assert.match(await page.locator('.own-player .player-copy > strong').innerText(),/Learner/);
    assert.match(await page.locator('.player-row').first().innerText(),/Practice opponent/);
    await page.getByRole('button',{name:'Review whole game',exact:true}).waitFor();
    const firstStep=await actionResponse(reportRoute,()=>page.getByRole('button',{name:'Review whole game',exact:true}).click());
    assert.equal(firstStep.review.entries.length,1);
    await page.getByRole('button',{name:'Pause review',exact:true}).click();
    await page.getByRole('button',{name:'Resume review',exact:true}).waitFor();
    const savedReview=responseFor(reportRoute,'GET');await page.reload();
    const partial=(await (await savedReview).json()).review;assert.ok(partial.entries.length>=1&&partial.entries.length<4,'Pause keeps partial progress');
    await page.getByRole('button',{name:'Resume review',exact:true}).click();
    await page.getByRole('button',{name:'Review complete',exact:true}).waitFor({timeout:30000});
    const report=(await (await context.request.get(base+reportRoute)).json()).review;
    assert.equal(report.complete,true);assert.equal(report.entries.length,4);assert.match(report.engine,/Stockfish/);assert.equal(report.entries.at(-1).evaluation.value,'0-1');
    for(const entry of report.entries){assert.equal(entry.analysis.played.move,imported.game.moves[entry.ply-1]);assert.equal(entry.analysis.fen,engine.replay(imported.game.moves.slice(0,entry.ply-1),imported.game.initialFen).fen());}
    if(evidence) await page.screenshot({path:path.join(evidence,'09-full-game-report.png'),fullPage:true});
    const graphPosition=page.getByRole('slider',{name:'Review position',exact:true});await graphPosition.focus();await graphPosition.press('Home');await graphPosition.press('ArrowRight');
    await page.getByRole('button',{name:'f3, white pawn',exact:true}).waitFor();
    assert.equal(await page.locator('.move-row button[aria-current=step]').getAttribute('aria-label'),'Move 1, white, f3');
    await page.getByLabel('Review as',{exact:true}).selectOption('w');
    assert.ok((await page.locator('.key-moves button').allTextContents()).every(text=>!text.includes('Qh4')),'White filter excludes Black key moves');
    await page.getByLabel('Review as',{exact:true}).selectOption('both');
    await page.getByRole('button',{name:'Review key move 2, black, Qh4#',exact:true}).click();
    await page.getByRole('button',{name:'h4, black queen',exact:true}).waitFor();
    assert.match(await page.locator('.classification').innerText(),/Checkmate/);
    await page.getByRole('button',{name:'Game report',exact:true}).click();
    if(evidence) await page.screenshot({path:path.join(evidence,'10-reviewed-key-move.png'),fullPage:true});
    let extraAnalysis=0;const countAnalysis=req=>{if(new URL(req.url()).pathname==='/api/analyze')extraAnalysis++;};page.on('request',countAnalysis);
    const restoredReport=responseFor(reportRoute,'GET');await page.reload();assert.equal((await (await restoredReport).json()).review.complete,true);
    await page.getByRole('button',{name:'Review complete',exact:true}).waitFor();
    await page.getByRole('button',{name:'Move 1, white, f3',exact:true}).click();
    await page.locator('.coach-message-heading > strong').filter({hasText:'1. f3'}).waitFor();
    await page.getByText(report.entries[0].analysis.played.explanation,{exact:true}).waitFor();
    await page.getByRole('button',{name:'Move 2, black, Qh4#',exact:true}).click();
    await page.getByRole('button',{name:'h4, black queen',exact:true}).waitFor();
    assert.equal(extraAnalysis,0,'Saved report navigation does not rerun the engine');page.off('request',countAnalysis);
    const unchanged=(await (await context.request.get(base+`/api/games/${imported.game.id}`)).json()).game;
    assert.deepEqual(unchanged.moves,imported.game.moves);assert.equal(unchanged.revision,imported.game.revision);
    await page.setViewportSize({width:390,height:844});
    await navigation.getByRole('button',{name:'Play bots',exact:true}).click();
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile horizontal overflow');
    assert.ok(await page.getByRole('button',{name:'Your account',exact:true}).isVisible(),'Mobile account access');
    if(evidence) await page.screenshot({path:path.join(evidence,'07-mobile-game.png'),fullPage:false});
    await page.getByRole('button',{name:'Game report',exact:true}).click();
    await page.getByLabel('Review as',{exact:true}).selectOption('b');
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile report has no horizontal overflow');
    if(evidence) await page.screenshot({path:path.join(evidence,'11-mobile-report.png'),fullPage:true});
    await page.getByRole('button',{name:'Game report',exact:true}).click();
    await page.getByRole('button',{name:'Open settings',exact:true}).click();
    await page.getByRole('dialog',{name:'Settings',exact:true}).waitFor();
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile settings overflow');
    if(evidence) await page.screenshot({path:path.join(evidence,'08-mobile-settings.png'),fullPage:false});
    await page.getByRole('button',{name:'Close dialog',exact:true}).click();
    await page.setViewportSize({width:1440,height:960});
    await page.getByRole('button',{name:'Set up position',exact:true}).click();
    const editor=page.getByRole('dialog',{name:'Set up position',exact:true}),editorBoard=editor.getByRole('group',{name:'Position editor board',exact:true});
    const savePosition=editor.getByRole('button',{name:'Save & analyze position',exact:true});
    await editor.getByRole('button',{name:'Clear board',exact:true}).click();assert.equal(await savePosition.isEnabled(),false);
    for(const [piece,square] of [['white king','e1'],['black king','e8'],['white rook','h1'],['black rook','a8']]){
      await editor.getByRole('button',{name:`Place ${piece}`,exact:true}).click();await editorBoard.getByRole('button',{name:`${square}, empty`,exact:true}).click();
    }
    await editor.getByLabel('Side to move',{exact:true}).selectOption('b');
    await editor.getByLabel('White O-O',{exact:true}).check();await editor.getByLabel('Black O-O-O',{exact:true}).check();
    await editor.getByLabel('Halfmove clock',{exact:true}).fill('7');await editor.getByLabel('Move number',{exact:true}).fill('12');
    await editorBoard.getByRole('button',{name:'h1, white rook',exact:true}).dragTo(editorBoard.getByRole('button',{name:'h2, empty',exact:true}));
    assert.equal(await savePosition.isEnabled(),false,'Moving a castling rook requires correcting rights');
    await editor.getByRole('button',{name:'Move pieces',exact:true}).click();await editorBoard.getByRole('button',{name:'h2, white rook',exact:true}).click();await editorBoard.getByRole('button',{name:'h1, empty',exact:true}).click();
    await editorBoard.getByRole('button',{name:'h1, white rook',exact:true}).dragTo(editor.getByRole('button',{name:'Remove pieces',exact:true}));
    assert.equal(await savePosition.isEnabled(),false);
    await editor.getByRole('button',{name:'Place white rook',exact:true}).dragTo(editorBoard.getByRole('button',{name:'h1, empty',exact:true}));
    const customFen='r3k3/8/8/8/8/8/8/4K2R b Kq - 7 12';assert.equal(await editor.getByLabel('Current FEN',{exact:true}).inputValue(),customFen);
    await editor.getByLabel('Load FEN',{exact:true}).fill('invalid');await editor.getByRole('button',{name:'Load position',exact:true}).click();
    assert.equal(await editor.getByLabel('Current FEN',{exact:true}).inputValue(),customFen,'Invalid FEN leaves edited board intact');
    await editor.getByLabel('Load FEN',{exact:true}).fill('4k3/8/8/3pP3/8/8/8/4K3 w - d6 0 12');await editor.getByRole('button',{name:'Load position',exact:true}).click();assert.equal(await editor.getByLabel('En passant',{exact:true}).inputValue(),'d6');
    await editor.getByLabel('Load FEN',{exact:true}).fill(customFen);await editor.getByRole('button',{name:'Load position',exact:true}).click();await editor.getByLabel('Study title',{exact:true}).fill('Rook study');
    if(evidence)await page.screenshot({path:path.join(evidence,'16-custom-position-editor.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});await editor.getByRole('button',{name:'Flip board',exact:true}).click();
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile editor has no horizontal overflow');
    assert.equal(await editorBoard.locator('.square').first().getAttribute('aria-label'),'h1, white rook');
    if(evidence)await page.screenshot({path:path.join(evidence,'17-mobile-position-editor.png'),fullPage:false});
    await page.setViewportSize({width:1440,height:960});
    const customAnalysis=responseFor('/api/analyze');
    const custom=await actionResponse('/api/positions',()=>savePosition.click(),201);assert.equal(custom.game.initialFen,customFen);assert.deepEqual(custom.game.moves,[]);
    const analyzed=await (await customAnalysis).json();assert.equal(analyzed.fen,customFen);assert.match(analyzed.engine,/Stockfish/);assert.ok(analyzed.lines.length);
    await page.locator('.coach-explanation').waitFor();if(evidence)await page.screenshot({path:path.join(evidence,'18-custom-position-analysis.png'),fullPage:true});
    const customRoute=`/api/games/${custom.game.id}`;const customReload=responseFor(customRoute,'GET');await page.reload();assert.equal((await (await customReload).json()).game.initialFen,customFen);
    await page.getByRole('button',{name:'Practice this position',exact:true}).click();
    const customSetup=page.getByRole('dialog',{name:'Practice this position',exact:true});
    await customSetup.getByText('Game options',{exact:false}).first().click();await customSetup.getByRole('button',{name:'1 min',exact:true}).click();
    const customPractice=await actionResponse(customRoute+'/practice',()=>customSetup.getByRole('button',{name:'Start position practice',exact:true}).click(),201);
    assert.equal(customPractice.game.color,'b');assert.equal(customPractice.game.initialFen,customFen);
    await page.waitForFunction(()=>document.querySelector('[aria-label=\"Your clock\"]')?.textContent==='0:59');assert.equal(await page.getByLabel('Opponent clock',{exact:true}).innerText(),'1:00','Only Black’s clock runs');
    const customReply=responseFor(`/api/games/${customPractice.game.id}/bot`);await enterMove('a8a7');assert.equal((await customReply).status(),200);
    await page.getByRole('button',{name:'Return to source study',exact:true}).click();await page.getByRole('button',{name:'a8, black rook',exact:true}).waitFor();
    const preservedCustom=(await (await context.request.get(base+customRoute)).json()).game;assert.deepEqual(preservedCustom.moves,[]);assert.equal(preservedCustom.initialFen,customFen);
    await page.setViewportSize({width:1440,height:960});
    const catalogueReady=responseFor('/api/openings','GET');await navigation.getByRole('button',{name:'Openings',exact:true}).click();
    const firstCatalogue=await (await catalogueReady).json();assert.equal(firstCatalogue.source.count,3810);assert.equal(firstCatalogue.items.length,24);
    const nextCatalogue=responseFor('/api/openings','GET');await page.getByRole('button',{name:'Next page',exact:true}).click();const secondCatalogue=await (await nextCatalogue).json();assert.equal(secondCatalogue.page,1);assert.ok(!secondCatalogue.items.some(item=>firstCatalogue.items.some(other=>other.id===item.id)));
    await page.getByLabel('Search openings',{exact:true}).fill('nonexistent_chess_opening_zzzz');await page.getByRole('heading',{name:'No matching openings.',exact:true}).waitFor();
    await page.getByLabel('ECO group',{exact:true}).selectOption('C');
    const italianResults=page.waitForResponse(response=>{const url=new URL(response.url());return url.pathname==='/api/openings'&&url.searchParams.get('q')==='Italian Game'&&url.searchParams.get('eco')==='C';});
    await page.getByLabel('Search openings',{exact:true}).fill('Italian Game');const italianCatalogue=await (await italianResults).json();assert.ok(italianCatalogue.items.every(item=>item.eco.startsWith('C')));
    const italianId=italianCatalogue.items.find(item=>item.name==='Italian Game').id;
    const italianResponse=responseFor('/api/openings/'+italianId,'GET');await page.getByRole('button',{name:'Open Italian Game, C50',exact:true}).click();const italian=(await (await italianResponse).json()).opening;
    await page.getByRole('group',{name:'Opening preview board',exact:true}).getByRole('button',{name:'c4, white bishop',exact:true}).waitFor();
    await page.getByRole('button',{name:'Opening first position',exact:true}).click();await page.getByRole('group',{name:'Opening preview board',exact:true}).getByRole('button',{name:'e2, white pawn',exact:true}).waitFor();
    await page.getByRole('button',{name:'Opening move 1, black, e5',exact:true}).click();
    if(evidence)await page.screenshot({path:path.join(evidence,'19-local-openings.png'),fullPage:true});
    const openingStudy=await actionResponse(`/api/openings/${italianId}/study`,()=>page.getByRole('button',{name:'Practice this position',exact:true}).click(),201);
    assert.deepEqual(openingStudy.game.moves,italian.moves);assert.equal(openingStudy.game.opening.name,'Italian Game');
    const openingSetup=page.getByRole('dialog',{name:'Practice this position',exact:true});
    const openingPractice=await actionResponse(`/api/games/${openingStudy.game.id}/practice`,()=>openingSetup.getByRole('button',{name:'Start position practice',exact:true}).click(),201);
    assert.deepEqual(openingPractice.game.moves,italian.moves.slice(0,2));assert.equal(openingPractice.game.color,'w');
    const openingBot=responseFor(`/api/games/${openingPractice.game.id}/bot`);await enterMove('g1f3');const openingReply=(await (await openingBot).json()).game;assert.equal(openingReply.moves.length,4);assert.equal(engine.replay(openingReply.moves).history().length,4);
    if(evidence)await page.screenshot({path:path.join(evidence,'20-opening-practice.png'),fullPage:true});
    await page.getByRole('button',{name:'Return to source study',exact:true}).click();await page.getByRole('button',{name:'Last position',exact:true}).click();
    await page.locator('.opening-recognition strong').filter({hasText:'Italian Game'}).waitFor();assert.match(await page.locator('.opening-recognition').innerText(),/Played line/);
    const retainedOpening=(await (await context.request.get(base+`/api/games/${openingStudy.game.id}`)).json()).game;assert.deepEqual(retainedOpening.moves,italian.moves);
    const openingReload=responseFor(`/api/games/${openingStudy.game.id}`,'GET');await page.reload();assert.equal((await (await openingReload).json()).game.opening.id,italianId);
    await page.locator('.opening-recognition strong').filter({hasText:'Italian Game'}).waitFor();
    await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Explore opening',exact:true}).click();
    await page.locator('.opening-title h3').filter({hasText:'Italian Game'}).waitFor();
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile opening overflow');
    await page.getByRole('button',{name:'Flip opening board',exact:true}).click();
    if(evidence)await page.screenshot({path:path.join(evidence,'21-mobile-openings.png'),fullPage:true});
    await page.setViewportSize({width:1440,height:960});
    const trainingCatalog=responseFor('/api/training/catalog','GET');await navigation.getByRole('button',{name:'Puzzles',exact:true}).click();
    const trainingMeta=await (await trainingCatalog).json();assert.equal(trainingMeta.count,6100952);assert.ok(trainingMeta.themes.mateIn2>0);
    await page.locator('.training-mode-picker').getByRole('button',{name:/^Custom practice/}).click();
    await page.getByLabel('Theme',{exact:true}).selectOption('mateIn2');
    await page.getByLabel('Minimum source rating',{exact:true}).fill('1000');await page.getByLabel('Maximum source rating',{exact:true}).fill('2000');
    if(evidence)await page.screenshot({path:path.join(evidence,'22-training-catalogue.png'),fullPage:true});
    let training=(await actionResponse('/api/training/start',()=>page.getByRole('button',{name:'Start training',exact:false}).click(),201)).attempt;
    assert.equal(training.puzzle.solution,undefined);assert.equal(training.solution,undefined);assert.ok(training.puzzle.themes.includes('mateIn2'));assert.ok(training.puzzle.rating>=1000&&training.puzzle.rating<=2000);
    const {DatabaseSync}=require('node:sqlite');const puzzleSource=new DatabaseSync(process.env.CHESSLAB_PUZZLES||path.join(root,'data/puzzles/catalogue.sqlite'),{readOnly:true});
    let sourcePuzzle;try{sourcePuzzle=puzzleSource.prepare('SELECT * FROM puzzles WHERE id=?').get(training.puzzle.id);}finally{puzzleSource.close();}
    const sourceLine=sourcePuzzle.moves.split(' '),solution=sourceLine.slice(1),trainingId=training.id;
    const trainingBoard=new Chess(sourcePuzzle.fen);trainingBoard.move({from:sourceLine[0].slice(0,2),to:sourceLine[0].slice(2,4),promotion:sourceLine[0][4]});assert.equal(training.puzzle.fen,trainingBoard.fen());
    const wrongTraining=trainingBoard.moves({verbose:true}).find(move=>{const uci=move.from+move.to+(move.promotion||'');if(uci===solution[0])return false;const testBoard=new Chess(trainingBoard.fen());testBoard.move(move);return !testBoard.isCheckmate();});assert.ok(wrongTraining);
    async function trainingMove(move){await page.getByLabel('Training move',{exact:true}).fill(move);return actionResponse('/api/training/'+training.id+'/action',()=>page.getByRole('button',{name:'Play move',exact:true}).click());}
    let trainingReply=await trainingMove(wrongTraining.from+wrongTraining.to+(wrongTraining.promotion||''));assert.equal(trainingReply.correct,false);training=trainingReply.attempt;assert.equal(training.mistakes,1);assert.deepEqual(training.moves,[]);
    training=(await actionResponse('/api/training/'+training.id+'/action',()=>page.getByRole('button',{name:'Show hint',exact:true}).click())).attempt;assert.equal(training.assisted,true);assert.equal(training.puzzle.solution,undefined);
    training=(await trainingMove(solution[0])).attempt;assert.deepEqual(training.moves,solution.slice(0,2));assert.equal(training.hint,null);
    await page.reload();const restoredTraining=responseFor('/api/training','GET');await navigation.getByRole('button',{name:'Puzzles',exact:true}).click();const restoredAttempt=(await (await restoredTraining).json()).attempt;assert.equal(restoredAttempt.id,trainingId);assert.deepEqual(restoredAttempt.moves,training.moves);
    await page.getByLabel('Training move',{exact:true}).waitFor();
    if(evidence)await page.screenshot({path:path.join(evidence,'23-persisted-training.png'),fullPage:true});
    while(training.state==='active'){training=(await trainingMove(solution[training.moves.length])).attempt;}
    assert.equal(training.state,'solved');assert.deepEqual(training.moves,solution);
    await page.getByRole('heading',{name:'You found the line.',exact:true}).waitFor();
    const puzzleAnalysis=responseFor('/api/analyze');const solvedStudy=await actionResponse('/api/training/'+training.id+'/study',()=>page.getByRole('button',{name:'Analyze solution',exact:true}).click(),201);
    assert.equal(solvedStudy.game.initialFen,sourcePuzzle.fen);assert.deepEqual(solvedStudy.game.moves,sourceLine);assert.equal(solvedStudy.game.result,training.puzzle.side==='w'?'1-0':'0-1');assert.equal((await puzzleAnalysis).status(),200);
    await page.locator('.own-player').getByText(training.puzzle.side==='w'?'White won':'Black won',{exact:true}).waitFor();
    await page.locator('.engine-receipt').filter({hasText:'Stockfish 19'}).waitFor();
    assert.deepEqual((await (await context.request.get(base+'/api/games/'+openingStudy.game.id)).json()).game.moves,italian.moves,'Opening source remains intact after puzzle analysis');
    if(evidence)await page.screenshot({path:path.join(evidence,'24-puzzle-native-analysis.png'),fullPage:true});
    const retryState=responseFor('/api/training','GET');await navigation.getByRole('button',{name:'Puzzles',exact:true}).click();const retryStats=await (await retryState).json();assert.equal(retryStats.totals.solved,1);assert.equal(retryStats.totals.unassisted,0);
    await page.locator('.training-mode-picker').getByRole('button',{name:/^Custom practice/}).click();
    await page.getByLabel('Retry previous mistakes',{exact:true}).check();await page.getByLabel('Maximum source rating',{exact:true}).fill('2000');
    training=(await actionResponse('/api/training/start',()=>page.getByRole('button',{name:'Start training',exact:false}).click(),201)).attempt;assert.equal(training.puzzle.id,sourcePuzzle.id);
    training=(await actionResponse('/api/training/'+training.id+'/action',()=>page.getByRole('button',{name:'Reveal solution',exact:true}).click())).attempt;assert.equal(training.state,'revealed');assert.deepEqual(training.solution,solution);
    await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'First position',exact:true}).click();await page.getByRole('button',{name:'Next move',exact:true}).click();await page.getByRole('button',{name:'Flip training board',exact:true}).click();
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile training overflow');
    if(evidence)await page.screenshot({path:path.join(evidence,'25-mobile-training.png'),fullPage:true});
    training=(await actionResponse('/api/training/start',()=>page.getByRole('button',{name:'Try again',exact:true}).click(),201)).attempt;assert.equal(training.assisted,false);
    while(training.state==='active'){training=(await trainingMove(solution[training.moves.length])).attempt;}
    assert.equal(training.mistakes,0);assert.equal(training.assisted,false);
    const finalTraining=(await (await context.request.get(base+'/api/training')).json());assert.equal(finalTraining.totals.attempts,3);assert.equal(finalTraining.totals.solved,2);assert.equal(finalTraining.totals.unassisted,1);assert.equal(finalTraining.history.length,3);
    await page.setViewportSize({width:1440,height:960});
    await page.locator('.training-mode-picker').getByRole('button',{name:/^Rated/}).click();
    await page.getByLabel('Puzzle difficulty',{exact:true}).selectOption('standard');
    training=(await actionResponse('/api/training/start',()=>page.getByRole('button',{name:/^Start rated puzzle/}).click(),201)).attempt;
    assert.equal(training.mode,'rated');assert.equal(training.difficulty,'standard');assert.ok(training.puzzle.rating>=1050&&training.puzzle.rating<=1350);
    training=(await actionResponse('/api/training/'+training.id+'/action',()=>page.getByRole('button',{name:'Show hint',exact:true}).click())).attempt;
    assert.equal(training.ratingChange.result,'loss');const ratedLoss=training.ratingChange.after;assert.ok(ratedLoss<1500);
    training=(await actionResponse('/api/training/'+training.id+'/action',()=>page.getByRole('button',{name:'Reveal solution',exact:true}).click())).attempt;assert.equal(training.ratingChange.after,ratedLoss);
    await page.getByLabel('Puzzle difficulty',{exact:true}).selectOption('extra');
    training=(await actionResponse('/api/training/start',()=>page.getByRole('button',{name:/^Next rated puzzle/}).click(),201)).attempt;assert.equal(training.mode,'rated');assert.equal(training.difficulty,'extra');
    function sourceSolution(id){const source=new DatabaseSync(process.env.CHESSLAB_PUZZLES||path.join(root,'data/puzzles/catalogue.sqlite'),{readOnly:true});try{return source.prepare('SELECT moves FROM puzzles WHERE id=?').get(id).moves.split(' ').slice(1);}finally{source.close();}}
    const ratedLine=sourceSolution(training.puzzle.id);
    while(training.state==='active'){training=(await trainingMove(ratedLine[training.moves.length])).attempt;}
    assert.equal(training.ratingChange.result,'win');assert.equal(training.ratingChange.before,ratedLoss);assert.ok(training.ratingChange.delta>0);
    const afterRated=(await (await context.request.get(base+'/api/training')).json());assert.equal(afterRated.profile.ratedCount,2);assert.equal(afterRated.profile.rating,training.ratingChange.after);
    await page.getByLabel('Local puzzle rating',{exact:true}).filter({hasText:String(afterRated.profile.rating)}).waitFor();
    if(evidence)await page.screenshot({path:path.join(evidence,'26-rated-puzzle-result.png'),fullPage:true});
    await page.locator('.training-mode-picker').getByRole('button',{name:/^Daily/}).click();
    training=(await actionResponse('/api/training/start',()=>page.getByRole('button',{name:/^Play daily puzzle/}).click(),201)).attempt;
    assert.equal(training.mode,'daily');const dailyAttemptId=training.id,dailyDate=training.dailyDate,dailyLine=sourceSolution(training.puzzle.id);
    await page.reload();const dailyRestored=responseFor('/api/training','GET');await navigation.getByRole('button',{name:'Puzzles',exact:true}).click();const dailyState=await (await dailyRestored).json();assert.equal(dailyState.attempt.id,dailyAttemptId);assert.equal(dailyState.attempt.mode,'daily');
    await page.locator('.training-daily-progress strong').filter({hasText:dailyDate}).waitFor();
    while(training.state==='active'){training=(await trainingMove(dailyLine[training.moves.length])).attempt;}
    assert.equal(training.state,'solved');assert.equal(training.ratingChange,null);
    let afterDaily=(await (await context.request.get(base+'/api/training')).json());assert.equal(afterDaily.profile.rating,afterRated.profile.rating);assert.equal(afterDaily.profile.ratedCount,2);assert.equal(afterDaily.daily.streak,1);assert.deepEqual(afterDaily.daily.completedDates,[dailyDate]);
    await page.getByText('Today’s puzzle is complete. Return tomorrow for another.',{exact:true}).waitFor();
    if(evidence)await page.screenshot({path:path.join(evidence,'27-daily-complete.png'),fullPage:true});
    await page.locator('.training-mode-picker').getByRole('button',{name:/^Rated/}).click();await page.locator('.training-mode-picker').getByRole('button',{name:/^Daily/}).click();
    training=(await actionResponse('/api/training/start',()=>page.getByRole('button',{name:/^Return to daily puzzle/}).click(),201)).attempt;assert.equal(training.id,dailyAttemptId);assert.equal(training.state,'solved');
    await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile puzzle-mode overflow');
    if(evidence)await page.screenshot({path:path.join(evidence,'28-mobile-daily.png'),fullPage:true});
    training=(await actionResponse('/api/training/start',()=>page.getByRole('button',{name:'Try again',exact:true}).click(),201)).attempt;assert.equal(training.mode,'custom');assert.equal(training.dailyDate,null);
    training=(await actionResponse('/api/training/'+training.id+'/action',()=>page.getByRole('button',{name:'Reveal solution',exact:true}).click())).attempt;
    afterDaily=(await (await context.request.get(base+'/api/training')).json());assert.equal(afterDaily.profile.ratedCount,2);assert.deepEqual(afterDaily.daily.completedDates,[dailyDate]);assert.equal(afterDaily.totals.attempts,7);
    await page.setViewportSize({width:1440,height:1000});
    await page.locator('.training-mode-picker').getByRole('button',{name:/^Puzzle Rush/}).click();
    await page.getByRole('group',{name:'Rush duration',exact:true}).getByRole('button',{name:/^Survival/}).click();
    let rush=(await actionResponse('/api/rush/start',()=>page.getByRole('button',{name:/^Start Rush/}).click(),201)).run;
    assert.equal(rush.variant,'survival');assert.equal(rush.deadline,null);assert.equal(rush.current.puzzle.solution,undefined);
    await page.getByRole('timer',{name:'Rush time remaining'}).filter({hasText:'∞'}).waitFor();assert.equal(await page.getByRole('button',{name:'Show hint',exact:true}).count(),0);
    const firstRushId=rush.id,firstRushPuzzle=rush.current.puzzle.id,firstRushRating=rush.current.puzzle.rating,firstRushLine=sourceSolution(firstRushPuzzle);
    async function rushMove(move){await page.getByLabel('Rush move',{exact:true}).fill(move);return actionResponse('/api/rush/'+rush.id+'/action',()=>page.getByRole('button',{name:'Play Rush move',exact:true}).click());}
    const rushBoard=page.getByRole('group',{name:'Rush puzzle board',exact:true});const openingRushMove=firstRushLine[0];
    const clickedRush=responseFor('/api/rush/'+rush.id+'/action');await rushBoard.getByRole('button',{name:new RegExp('^'+openingRushMove.slice(0,2)+',')}).click();await rushBoard.getByRole('button',{name:new RegExp('^'+openingRushMove.slice(2,4)+',')}).click();
    if(openingRushMove[4])await page.getByRole('dialog',{name:'Choose Rush promotion'}).getByRole('button',{name:'Promote to '+{q:'queen',r:'rook',b:'bishop',n:'knight'}[openingRushMove[4]],exact:true}).click();
    rush=(await (await clickedRush).json()).run;
    while(rush.current.puzzle.id===firstRushPuzzle&&rush.state==='active')rush=(await rushMove(firstRushLine[rush.current.moves.length])).run;
    assert.equal(rush.score,1);assert.equal(rush.items[0].result,'solved');assert.ok(rush.current.puzzle.rating>=firstRushRating);assert.notEqual(rush.current.puzzle.id,firstRushPuzzle);
    await page.getByLabel('Rush score',{exact:true}).filter({hasText:'1'}).waitFor();
    if(evidence)await page.screenshot({path:path.join(evidence,'29-rush-survival.png'),fullPage:true});
    await page.reload();const rushNavState=responseFor('/api/training','GET'),rushRestored=responseFor('/api/rush','GET');await navigation.getByRole('button',{name:'Puzzles',exact:true}).click();assert.equal((await (await rushNavState).json()).rush.id,firstRushId);let resumedRush=(await (await rushRestored).json()).run;assert.equal(resumedRush.id,rush.id);assert.equal(resumedRush.score,1);assert.equal(resumedRush.current.puzzle.id,rush.current.puzzle.id);
    const currentRushBoard=new Chess(rush.current.puzzle.fen),expectedRushLine=sourceSolution(rush.current.puzzle.id);for(const move of rush.current.moves)currentRushBoard.move({from:move.slice(0,2),to:move.slice(2,4),promotion:move[4]});
    const wrongRush=currentRushBoard.moves({verbose:true}).find(move=>{const candidate=move.from+move.to+(move.promotion||'');if(candidate===expectedRushLine[rush.current.moves.length])return false;const board=new Chess(currentRushBoard.fen());board.move(move);return !board.isCheckmate();});assert.ok(wrongRush);
    rush=(await rushMove(wrongRush.from+wrongRush.to+(wrongRush.promotion||''))).run;assert.equal(rush.mistakes,1);assert.equal(rush.score,1);assert.equal(rush.items[1].result,'failed');
    for(let count=0;count<2;count++)rush=(await actionResponse('/api/rush/'+rush.id+'/action',()=>page.getByRole('button',{name:'Skip · lose a life',exact:true}).click())).run;
    assert.equal(rush.state,'finished');assert.equal(rush.reason,'mistakes');assert.equal(rush.mistakes,3);assert.equal(rush.score,1);
    await page.getByRole('heading',{name:'Three strikes. A fresh start awaits.',exact:true}).waitFor();await page.getByRole('button',{name:'Open Survival Rush score 1',exact:true}).waitFor();
    const savedRush=await (await context.request.get(base+'/api/rush/'+rush.id)).json();assert.equal(savedRush.bests.survival,1);
    if(evidence)await page.screenshot({path:path.join(evidence,'30-rush-results.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Flip Rush board',exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile Rush overflow');
    if(evidence)await page.screenshot({path:path.join(evidence,'31-mobile-rush.png'),fullPage:true});
    training=(await actionResponse('/api/rush/'+rush.id+'/retry',()=>page.getByRole('button',{name:'Retry Rush puzzle 2, failed',exact:true}).click(),201)).attempt;assert.equal(training.mode,'custom');assert.equal(training.puzzle.id,rush.items[1].puzzleId);
    training=(await actionResponse('/api/training/'+training.id+'/action',()=>page.getByRole('button',{name:'Reveal solution',exact:true}).click())).attempt;assert.equal(training.state,'revealed');
    assert.deepEqual((await (await context.request.get(base+'/api/rush/'+rush.id)).json()).run,savedRush.run,'Retry cannot alter the saved Rush');
    const afterRush=(await (await context.request.get(base+'/api/training')).json());assert.deepEqual(afterRush.profile,afterDaily.profile);assert.deepEqual(afterRush.daily.completedDates,[dailyDate]);
    await page.setViewportSize({width:1440,height:1000});await page.locator('.training-mode-picker').getByRole('button',{name:/^Puzzle Rush/}).click();
    rush=(await actionResponse('/api/rush/start',()=>page.getByRole('button',{name:/^Start Rush/}).click(),201)).run;assert.equal(rush.variant,'3min');assert.equal(rush.deadline-rush.startedAt,180000);
    await page.getByRole('timer',{name:'Rush time remaining'}).filter({hasText:/^[23]:[0-5][0-9]$/}).waitFor();
    if(evidence)await page.screenshot({path:path.join(evidence,'32-timed-rush.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});await page.getByRole('timer',{name:'Rush mobile time remaining',exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No timed mobile Rush overflow');if(evidence)await page.screenshot({path:path.join(evidence,'33-mobile-rush-clock.png'),fullPage:true});
    await page.setViewportSize({width:1440,height:1000});
    rush=(await actionResponse('/api/rush/'+rush.id+'/action',()=>page.getByRole('button',{name:'End run',exact:true}).click())).run;assert.equal(rush.state,'finished');assert.equal(rush.reason,'ended');
    await page.getByRole('button',{name:'Open Survival Rush score 1',exact:true}).click();await page.getByRole('heading',{name:'Three strikes. A fresh start awaits.',exact:true}).waitFor();
    const curriculumLoaded=responseFor('/api/curriculum','GET');await navigation.getByRole('button',{name:'Learn',exact:true}).click();const curriculum=await (await curriculumLoaded).json();assert.equal(curriculum.lessons.length,12);assert.equal(curriculum.courses.length,4);
    await page.getByRole('heading',{name:'Build the habit. Understand the game.',exact:true}).waitFor();
    if(evidence)await page.screenshot({path:path.join(evidence,'34-learning-path.png'),fullPage:true});
    let courseSession=(await actionResponse('/api/course-lessons/rook-lines/start',()=>page.getByRole('button',{name:'Rooks travel in straight lines',exact:true}).click(),201)).session;
    async function courseMove(move){await page.getByLabel('Lesson move',{exact:true}).fill(move);const data=await actionResponse('/api/course-lessons/'+courseSession.lessonId+'/action',()=>page.getByRole('button',{name:'Play lesson move',exact:true}).click());courseSession=data.session;return data;}
    let courseReply=await courseMove('a1a2');assert.equal(courseReply.correct,false);assert.deepEqual(courseSession.current.moves,[]);assert.ok(!courseReply.progress.completed.includes('rook-lines'));
    const lessonBoard=page.getByRole('group',{name:'Lesson challenge board',exact:true}),rookClick=responseFor('/api/course-lessons/rook-lines/action');await lessonBoard.getByRole('button',{name:/^a1, white rook/}).click();await lessonBoard.getByRole('button',{name:/^a7, black bishop/}).click();courseSession=(await (await rookClick).json()).session;assert.equal(courseSession.current.state,'solved');assert.equal(courseSession.state,'active');
    courseSession=(await actionResponse('/api/course-lessons/rook-lines/action',()=>page.getByRole('button',{name:/^Continue to challenge 2/}).click())).session;assert.equal(courseSession.step,1);
    await page.reload();const resumedCourses=responseFor('/api/lesson-progress','GET');await navigation.getByRole('button',{name:'Learn',exact:true}).click();assert.equal((await (await resumedCourses).json()).sessions.find(x=>x.lessonId==='rook-lines').step,1);
    courseSession=(await actionResponse('/api/course-lessons/rook-lines/start',()=>page.getByRole('button',{name:/^Continue lesson/}).click(),201)).session;assert.equal(courseSession.step,1);
    courseReply=await courseMove('h8h2');assert.equal(courseSession.state,'complete');assert.ok(courseReply.progress.completed.includes('rook-lines'));assert.ok(courseReply.progress.completed.includes('safe-king'));
    await page.getByText('Both challenges complete.',{exact:true}).waitFor();
    if(evidence)await page.screenshot({path:path.join(evidence,'35-lesson-complete.png'),fullPage:true});
    courseSession=(await actionResponse('/api/course-lessons/bishop-diagonals/start',()=>page.getByRole('button',{name:/^Next lesson/}).click(),201)).session;assert.equal(courseSession.lessonId,'bishop-diagonals');
    await courseMove('c1g5');courseSession=(await actionResponse('/api/course-lessons/bishop-diagonals/action',()=>page.getByRole('button',{name:/^Continue to challenge 2/}).click())).session;await courseMove('f8b4');assert.equal(courseSession.state,'complete');
    courseSession=(await actionResponse('/api/course-lessons/knight-jumps/start',()=>page.getByRole('button',{name:/^Next lesson/}).click(),201)).session;await courseMove('b1c3');courseSession=(await actionResponse('/api/course-lessons/knight-jumps/action',()=>page.getByRole('button',{name:/^Continue to challenge 2/}).click())).session;await courseMove('g8f6');assert.equal(courseSession.state,'complete');
    await page.getByRole('button',{name:/^← Learning path/}).click();await page.locator('.course-section').filter({hasText:'Meet your pieces'}).getByText('3 / 3 complete',{exact:true}).waitFor();
    if(evidence)await page.screenshot({path:path.join(evidence,'39-course-complete.png'),fullPage:true});await page.getByRole('button',{name:'Lesson library',exact:true}).click();await page.getByRole('searchbox',{name:'Search lessons',exact:true}).fill('promotion');await page.getByLabel('Lesson level',{exact:true}).selectOption('Intermediate');await page.getByLabel('Lesson topic',{exact:true}).selectOption('Endgames');await page.getByText('1 lesson found',{exact:true}).waitFor();
    if(evidence)await page.screenshot({path:path.join(evidence,'36-lesson-library.png'),fullPage:true});
    courseSession=(await actionResponse('/api/course-lessons/promotion-plan/start',()=>page.getByRole('button',{name:'Promote with a plan',exact:true}).click(),201)).session;
    const queenPromotion=responseFor('/api/course-lessons/promotion-plan/action');await lessonBoard.getByRole('button',{name:/^a7, white pawn/}).click();await lessonBoard.getByRole('button',{name:/^a8, empty/}).click();await page.getByRole('dialog',{name:'Choose lesson promotion'}).getByRole('button',{name:'Promote to queen',exact:true}).click();courseSession=(await (await queenPromotion).json()).session;assert.equal(courseSession.current.state,'solved');
    courseSession=(await actionResponse('/api/course-lessons/promotion-plan/action',()=>page.getByRole('button',{name:/^Continue to challenge 2/}).click())).session;
    courseReply=await courseMove('c7c8q');assert.equal(courseReply.correct,false);assert.deepEqual(courseSession.current.moves,[]);
    await page.setViewportSize({width:390,height:844});const rookPromotion=responseFor('/api/course-lessons/promotion-plan/action');await lessonBoard.getByRole('button',{name:/^c7, white pawn/}).click();await lessonBoard.getByRole('button',{name:/^c8, empty/}).click();await page.getByRole('dialog',{name:'Choose lesson promotion'}).getByRole('button',{name:'Promote to rook',exact:true}).click();courseSession=(await (await rookPromotion).json()).session;assert.equal(courseSession.state,'complete');assert.equal(courseSession.current.moves[0],'c7c8r');
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile lesson overflow');await page.getByRole('button',{name:'Flip lesson board',exact:true}).click();
    if(evidence)await page.screenshot({path:path.join(evidence,'37-mobile-lesson.png'),fullPage:true});
    await page.getByRole('button',{name:'Return to path',exact:true}).click();await page.getByRole('searchbox',{name:'Search lessons',exact:true}).fill('');await page.getByLabel('Lesson level',{exact:true}).selectOption('Advanced');await page.getByLabel('Lesson topic',{exact:true}).selectOption('Tactics');await page.getByText('2 lessons found',{exact:true}).waitFor();
    await page.setViewportSize({width:1440,height:1000});courseSession=(await actionResponse('/api/course-lessons/mating-net/start',()=>page.getByRole('button',{name:'Calculate a mating net',exact:true}).click(),201)).session;
    const authoredCourses=JSON.parse(fs.readFileSync(path.join(root,'server/curriculum.json'),'utf8')),matingLesson=authoredCourses.lessons.find(l=>l.id==='mating-net');
    for(let step=0;step<2;step++){while(courseSession.current.state==='active')await courseMove(matingLesson.challenges[step].solution[courseSession.current.moves.length]);if(step===0){assert.equal(courseSession.state,'active');courseSession=(await actionResponse('/api/course-lessons/mating-net/action',()=>page.getByRole('button',{name:/^Continue to challenge 2/}).click())).session;}}
    assert.equal(courseSession.state,'complete');const completeCourses=(await (await context.request.get(base+'/api/lesson-progress')).json());for(const id of ['safe-king','rook-lines','promotion-plan','mating-net'])assert.ok(completeCourses.completed.includes(id));
    if(evidence)await page.screenshot({path:path.join(evidence,'38-advanced-lesson.png'),fullPage:true});
    const collectionsLoaded=responseFor('/api/collections','GET');await navigation.getByRole('button',{name:'My games',exact:true}).click();assert.deepEqual((await (await collectionsLoaded).json()).collections,[]);
    const archiveBefore=(await (await context.request.get(base+'/api/games')).json()).games;
    const protectedStudy=(await (await context.request.get(base+gameRoute)).json()).game;
    async function newCollection(name){await page.getByRole('button',{name:'+ New collection',exact:true}).click();await page.getByRole('textbox',{name:'Collection name',exact:true}).fill(name);await page.getByRole('textbox',{name:'Collection description',exact:true}).fill('Positions worth another look.');return (await actionResponse('/api/collections',()=>page.getByRole('button',{name:'Create collection',exact:true}).click(),201)).collection;}
    let notebook=await newCollection('Opening notebook');await page.getByRole('heading',{name:'Ready for your first game.',exact:true}).waitFor();
    if(evidence)await page.screenshot({path:path.join(evidence,'40-empty-collection.png'),fullPage:true});
    await page.getByRole('button',{name:'Browse all games',exact:true}).click();
    await page.locator('.library-game input[type=checkbox]').nth(0).check();await page.locator('.library-game input[type=checkbox]').nth(1).check();
    await page.getByLabel('Add selected games to collection',{exact:true}).selectOption(notebook.id);
    notebook=(await actionResponse('/api/collections/'+notebook.id+'/games',()=>page.getByRole('button',{name:'Add selected',exact:true}).click())).collection;assert.equal(notebook.gameIds.length,2);
    const savedIds=[...notebook.gameIds];let favorites=await newCollection('Favorite studies');
    await page.getByRole('button',{name:'Open collection Opening notebook',exact:true}).click();await page.getByRole('checkbox',{name:'Select all visible games',exact:true}).check();await page.getByLabel('Add selected games to collection',{exact:true}).selectOption(favorites.id);
    favorites=(await actionResponse('/api/collections/'+favorites.id+'/games',()=>page.getByRole('button',{name:'Add selected',exact:true}).click())).collection;assert.deepEqual([...favorites.gameIds].sort(),[...savedIds].sort());
    await page.getByRole('button',{name:'Edit collection',exact:true}).click();await page.getByRole('textbox',{name:'Collection name',exact:true}).fill('Training notebook');await page.getByRole('textbox',{name:'Collection description',exact:true}).fill('Two ideas to revisit this week.');notebook=(await actionResponse('/api/collections/'+notebook.id,()=>page.getByRole('button',{name:'Save collection',exact:true}).click())).collection;assert.equal(notebook.name,'Training notebook');
    const searchTitle=archiveBefore.find(g=>g.id===savedIds[0]).title;
    await page.getByRole('searchbox',{name:'Search saved games',exact:true}).fill(searchTitle);assert.ok(await page.locator('.game-card').count()>0);await page.getByRole('searchbox',{name:'Search saved games',exact:true}).fill('no-such-saved-chess-game');await page.getByRole('heading',{name:'No matching games.',exact:true}).waitFor();await page.getByRole('searchbox',{name:'Search saved games',exact:true}).fill('');
    await page.getByLabel('Sort saved games',{exact:true}).selectOption('name');await page.getByLabel('Sort collections',{exact:true}).selectOption('name');assert.equal(await page.locator('.game-card').count(),2);
    if(evidence)await page.screenshot({path:path.join(evidence,'41-game-collections.png'),fullPage:true});
    await page.locator('.library-game input[type=checkbox]').first().check();notebook=(await actionResponse('/api/collections/'+notebook.id+'/games',()=>page.getByRole('button',{name:'Remove selected',exact:true}).click())).collection;assert.equal(notebook.gameIds.length,1);
    await page.reload();const reloadedCollections=responseFor('/api/collections','GET');await navigation.getByRole('button',{name:'My games',exact:true}).click();const persistedCollections=(await (await reloadedCollections).json()).collections;assert.deepEqual(persistedCollections.find(c=>c.id===notebook.id).gameIds,notebook.gameIds);assert.equal(persistedCollections.find(c=>c.id===favorites.id).gameIds.length,2);
    await page.getByRole('button',{name:'Open collection Training notebook',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.getByLabel('Open saved collection',{exact:true}).selectOption(favorites.id);assert.equal(await page.locator('.game-card').count(),2);await page.getByLabel('Open saved collection',{exact:true}).selectOption(notebook.id);assert.equal(await page.locator('.game-card').count(),1);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile collections overflow');
    if(evidence)await page.screenshot({path:path.join(evidence,'42-mobile-collection.png'),fullPage:true});
    await page.getByRole('button',{name:'Delete collection',exact:true}).click();await page.getByRole('button',{name:'Keep collection',exact:true}).click();assert.equal(await page.getByLabel('Open saved collection',{exact:true}).inputValue(),notebook.id);
    await page.getByRole('button',{name:'Delete collection',exact:true}).click();await actionResponse('/api/collections/'+notebook.id+'/delete',()=>page.getByRole('button',{name:'Delete collection permanently',exact:true}).click());await page.getByText('Collection deleted. All games and variations are preserved.',{exact:true}).waitFor();
    const archiveAfter=(await (await context.request.get(base+'/api/games')).json()).games;assert.deepEqual(archiveAfter.map(g=>g.id).sort(),archiveBefore.map(g=>g.id).sort());const retainedStudy=(await (await context.request.get(base+gameRoute)).json()).game;assert.deepEqual(retainedStudy.moves,protectedStudy.moves);assert.deepEqual(retainedStudy.study,protectedStudy.study);
    await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Open collection Favorite studies',exact:true}).click();assert.equal(await page.locator('.game-card').count(),2);
    if(evidence)await page.screenshot({path:path.join(evidence,'43-preserved-collection.png'),fullPage:true});
    const openingSaved=page.waitForResponse(r=>new URL(r.url()).pathname.match(/^\/api\/games\/[^/]+$/)&&r.request().method()==='GET');await page.locator('.game-card').first().click();const reopened=(await (await openingSaved).json()).game;assert.ok(savedIds.includes(reopened.id));assert.equal(reopened.title,archiveBefore.find(g=>g.id===reopened.id).title);
    assert.deepEqual(pageErrors, [], 'Browser JavaScript errors');
    assert.deepEqual(badResponses, [], 'Unexpected failing HTTP responses');
    assert.deepEqual(unexpectedRequests, [], 'No external resources or browser engine/model downloads');
    const receipt = { status: 'pass', checkedAt: new Date().toISOString(), engine: review.engine, checks: ['register and session cookie', 'typed e4 and real legal bot reply', 'engine review shown', 'saved game restored after reload', 'wrong/right lesson answers', 'wrong/right puzzle moves', 'progress restored after reload', 'bot search and visible identity', 'hint with engine evidence', 'nested study preserves original moves', 'board preference persists', 'mobile layout and account/settings access', 'no page errors or unexpected HTTP/model requests', 'whole game review with pause and reload resume', 'native evidence for every move and terminal result', 'key move filtering and cached navigation', 'practice from a saved nested branch with a real bot', 'practice undo boundary and position restart', 'practice provenance survives reload and source study return', 'mobile practice setup', 'custom piece placement, click and drag editing, removal and castling validation', 'FEN loading preserves invalid drafts and en passant', 'mobile custom position editor and flip', 'guest position draft survives cancelled sign-in', 'Black-first practice clock runs on the correct side', 'saved custom position with native analysis, reload and bot practice', 'local opening search, ECO filter and pagination', 'legal opening preview and selected move navigation', 'opening practice copies selected prefix and preserves full source', 'real native bot play from an opening', 'saved opening recognition and reload', 'mobile opening library and flip', 'full local puzzle catalogue and theme/rating filters', 'wrong move and hint preserve hidden solution and accepted position', 'multi-move training resumes after reload', 'finished puzzle creates separate study with native analysis', 'retry previous mistakes and reveal without unassisted credit', 'mobile playback, flip and clean retry persist correct totals', 'rated difficulty bands and once-only hint loss', 'clean rated solve updates profile and history', 'daily puzzle resumes its pinned date and position after reload', 'daily completion and replay cannot duplicate rating or streak credit', 'mobile rated/daily mode controls and progress', 'Survival board play scores a complete solution and advances difficulty', 'Rush restores mode, score and puzzle after reload', 'three failed puzzles end a run and persist personal bests', 'mobile Rush results retry separately without rating or daily changes', 'server-owned timed Rush clock, end and saved run history', 'guided course path and preserved starter lessons', 'wrong and correct lesson board moves, second-challenge reload recovery', 'all-challenge completion, full course completion and next lesson progression', 'lesson library search, level and topic filters', 'queen versus rook promotion and mobile lesson controls', 'advanced multi-move mating lessons and preserved account progress', 'named collections and multiple saved-game membership', 'collection details, saved-game search and sorting', 'membership removal and reload preserve other collections', 'mobile collection controls and cancelled deletion', 'confirmed collection deletion preserves all games and nested studies', 'saved collection game reopens through the normal board'], limitations: ['Uses isolated temporary SQLite, not the user database', 'Does not establish deployment or cross-browser support'] };
    if(evidence) receipt.video='local-user-flow.webm';
    const video=page.video();
    await context.close();
    if(evidence){if(video)fs.renameSync(await video.path(),path.join(evidence,'local-user-flow.webm'));fs.writeFileSync(path.join(evidence,'receipt.json'),JSON.stringify(receipt,null,2)+'\n');}
    console.log(JSON.stringify(receipt,null,2));
    if(evidence) console.log('Evidence saved to',evidence);
  } finally {
    try { await browser?.close(); }
    finally {
      engine.closeEngine();
      try {
        if (server) { server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); }
      } finally {
        try { state?.close(); }
        finally { fs.rmSync(temporary, { recursive: true, force: true }); }
      }
    }
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
