// Exercise the real component handlers without introducing a browser-test dependency.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const file=new URL('./main.jsx',import.meta.url);
const source=readFileSync(file,'utf8');
const between=(a,b)=>source.slice(source.indexOf(a),source.indexOf(b));
const line=name=>source.split('\n').find(row=>new RegExp(`^  (async )?function ${name}\\(`).test(row));
const auth=between('  async function authenticate(e){','  async function logout()');
const puzzle=between('  async function submitPuzzle(','  function boardMove(');
const lesson=between('  async function submitLesson(','  function selectLesson(');
const deferred=()=>{let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};};
function harness(action,{authReply=async()=>({user:{id:'A'},progress:{lessons:[],puzzles:[]}}),refresh=async()=>{},answer=async()=>({correct:true,complete:true,progress:{lessons:[],puzzles:['rook']}})}={}){
 const events=[],state={user:null,busy:false,progress:null,feedback:null,moves:null,complete:false};
 const refs={pendingAction:{current:action?{...action,sequence:4}:null},accountSequence:{current:0},exerciseSequence:{current:4},userRef:{current:null}};
 const env={...refs,authMode:'login',FormData:class{get(key){return key;}},startBusy:()=>{if(state.busy)return false;state.busy=true;return true;},endBusy:()=>{state.busy=false;events.push(['idle']);},setUser:v=>{state.user=v;},setProgress:v=>{state.progress=v;},setModal:v=>events.push(['modal',v]),setError:v=>events.push(['error',v]),setFeedback:v=>{state.feedback=v;},setPuzzleMoves:v=>{state.moves=v;},setPuzzleComplete:v=>{state.complete=v;},sound:()=>{},refreshGames:refresh,api:async(path,body)=>{events.push(['request',path,body]);return path==='/api/login'?authReply():answer(path,body);},createGame:async options=>events.push(['start',options,state.busy]),performImport:async pgn=>events.push(['import',pgn,state.busy]),performPosition:async payload=>events.push(['position',payload,state.busy])};
 const f=new Function(...Object.keys(env),`${line('installUser')}\n${auth}\n${puzzle}\n${lesson}\nreturn {authenticate,installUser,submitPuzzle,submitLesson};`)(...Object.values(env));
 return {...f,...refs,state,events,run:()=>f.authenticate({preventDefault(){},currentTarget:{}})};
}
test('cancel while authentication waits does not dispatch',async()=>{const wait=deferred(),h=harness({type:'start',options:{rating:800}},{authReply:()=>wait.promise});const run=h.run();h.pendingAction.current=null;wait.resolve({user:{id:'A'}});await run;assert.equal(h.events.some(e=>e[0]==='start'),false);});
test('refresh failure does not prevent original start payload',async()=>{const options={engineId:'maia3',rating:1200,color:'b'},h=harness({type:'start',options},{refresh:async()=>{throw new Error('refresh failed');}});await h.run();assert.deepEqual(h.events.find(e=>e[0]==='start'),['start',options,false]);assert.equal(h.pendingAction.current,null);});
test('puzzle resumes normalized full attempted moves using installed account',async()=>{const h=harness({type:'puzzle',id:'fork',moves:['f5e7','g8f7','e7d5']});await h.run();assert.deepEqual(h.events.find(e=>e[1]==='/api/puzzles/fork/answer')?.[2],{moves:['f5e7','g8f7','e7d5']});assert.equal(h.state.complete,true);assert.equal(h.state.user.id,'A');});
test('lesson and import retain submitted payload',async()=>{const h=harness({type:'lesson',id:'safe-king',choice:0});await h.run();assert.deepEqual(h.events.find(e=>e[1]==='/api/lessons/safe-king/answer')?.[2],{choice:0});const i=harness({type:'import',pgn:'1. e4 e5 *'});await i.run();assert.deepEqual(i.events.find(e=>e[0]==='import'),['import','1. e4 e5 *',false]);});
test('changed exercise cancels queued action',async()=>{const wait=deferred(),h=harness({type:'puzzle',id:'rook',moves:['d3e4']},{authReply:()=>wait.promise});const run=h.run();h.exerciseSequence.current++;wait.resolve({user:{id:'A'}});await run;assert.equal(h.events.some(e=>e[1]==='/api/puzzles/rook/answer'),false);});
test('late exercise response updates account progress but not another exercise',async()=>{const wait=deferred(),h=harness(null,{answer:()=>wait.promise});h.installUser({id:'A'});const run=h.submitPuzzle({id:'rook',moves:['d3e4']});h.exerciseSequence.current++;wait.resolve({correct:true,complete:true,progress:{puzzles:['rook'],lessons:[]}});await run;assert.deepEqual(h.state.progress.puzzles,['rook']);assert.equal(h.state.feedback,null);assert.equal(h.state.moves,null);});
test('late answer from different account is discarded',async()=>{const wait=deferred(),h=harness(null,{answer:()=>wait.promise});h.installUser({id:'A'});const run=h.submitPuzzle({id:'rook',moves:['d3e4']});h.installUser({id:'B'});wait.resolve({correct:true,complete:true,progress:{puzzles:['rook'],lessons:[]}});await run;assert.equal(h.state.progress,null);assert.equal(h.state.feedback,null);});
test('late initial guest account install must preserve queued import',async()=>{const wait=deferred(),h=harness({type:'import',pgn:'1. e4 e5 *'},{authReply:()=>wait.promise});const run=h.run();h.installUser(null);wait.resolve({user:{id:'A'}});await run;assert.ok(h.events.some(e=>e[0]==='import'),'bootstrap installUser(null) invalidated unchanged guest intent');});
test('older games refresh must not overwrite later completed refresh',async()=>{const old=deferred(),fresh=deferred();let calls=0,games;const accountSequence={current:0};const api=()=>++calls===1?old.promise:fresh.promise;const setGames=value=>{games=value;};const refreshGames=new Function('accountSequence','gamesSequence','api','setGames',`${line('refreshGames')};return refreshGames;`) (accountSequence,{current:0},api,setGames);const p1=refreshGames(),p2=refreshGames();fresh.resolve({games:[{id:'new-game'}]});await p2;old.resolve({games:[]});await p1;assert.deepEqual(games,[{id:'new-game'}]);});

test('position save resumes its exact submitted draft after authentication',async()=>{const payload={fen:'4k3/8/8/8/8/8/8/4K2R w - - 0 1',title:'My study'},h=harness({type:'position',payload});await h.run();assert.deepEqual(h.events.find(e=>e[0]==='position'),['position',payload,false]);});
