import React, {useId, useState} from 'react';
import {Piece} from './Board.jsx';

export const engineRatings=[250,400,550,700,850,1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000,2100,2200,2300,2400,2500,2600,2700,2900,3200];
export const assistanceDefaults={chat:true,evaluation:false,threats:false,suggestions:false,feedback:false,engine:false};
export const timeControls=[['No timer',0,0],['1 min',60,0],['1 + 1',60,1],['2 + 1',120,1],['3 + 2',180,2],['5 min',300,0],['5 + 5',300,5],['10 min',600,0],['15 + 10',900,10],['30 min',1800,0],['10 + 5',600,5],['20 min',1200,0],['60 min',3600,0]];
export function BotAvatar({bot,className=''}) {return bot?.avatar?<img className={`bot-avatar ${className}`} src={bot.avatar} alt="" width="80" height="80"/>:<span className={`bot-avatar engine-avatar ${className}`}><Piece type="n" color="b"/></span>;}
export function Crowns({count=0}) {return <span className="crowns" aria-label={`${count} of 3 crowns`}>{[1,2,3].map(n=><span key={n} className={n<=count?'earned':''} aria-hidden="true">♛</span>)}</span>;}
export default function BotSetup({bots,engines,progress,botId,engineId,rating,color,timeControl,assistance,onChange,onStart,disabled,busy,pending=false,compact=false}) {
  const id=useId(),[filter,setFilter]=useState(null),[search,setSearch]=useState('');
  if(pending)return <div className="bot-setup" aria-busy="true"><p className="opponent-description" role="status">Checking installed engines…</p><button type="button" className="button primary start-button" disabled>Play bot</button></div>;
  const bot=bots.find(b=>b.id===botId),engine=engines.find(e=>e.id===engineId),raw=!botId;
  const query=search.trim().toLocaleLowerCase();
  const filtered=bots.filter(item=>`${item.name} ${item.category} ${item.referenceRating||item.rating}`.toLocaleLowerCase().includes(query));
  const groups=[...new Set(filtered.map(item=>item.category))];
  const activeGroup=filter??bot?.category??groups[0];
  const chooseBot=bot=>onChange({botId:bot.id,rating:bot.rating});
  return <div className={`bot-setup ${compact?'compact':''}`}>
    <div className="opponent-introduction"><BotAvatar bot={bot}/><p>{raw?'Choose an engine and set the strength.':bot?.description||'Choose your opponent.'}</p></div>
    <div className="opponent-name"><strong>{raw?engine?.name||'Engine':bot?.name}</strong> <span>{!raw&&rating===bot?.rating?(bot?.referenceRating||rating):rating}</span><Crowns count={progress?.bots?.[botId]||0}/></div>
    <div className="opponent-tabs" aria-label="Opponent type"><button type="button" className={!raw?'active':''} onClick={()=>bots[0]&&chooseBot(bots[0])}>Bots <span>{bots.length}</span></button><button type="button" className={raw?'active':''} onClick={()=>onChange({botId:null,rating:1500})}>Engines <span>{engines.filter(e=>e.available).length}</span></button></div>
    {!raw?<>
      <div className="bot-search"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input type="search" aria-label="Search bots" placeholder="Find a bot by name or rating" value={search} onChange={event=>setSearch(event.target.value)}/></div>
      <div className="roster-caption"><span>{query?`${filtered.length} matching bots`:'Choose your challenge'}</span><span>{query?'Search results':`${bots.length} opponents`}</span></div>
      <div className="bot-roster">
        {groups.map(group=><section className="bot-group" key={group}>
          <button type="button" className="bot-group-title" aria-expanded={!!query||activeGroup===group} onClick={()=>setFilter(activeGroup===group?'':group)}><strong>{group.replaceAll('_',' ')}</strong><span>{filtered.filter(item=>item.category===group).length}</span><span className="group-chevron" aria-hidden="true">⌄</span></button>
          {(query||activeGroup===group)&&<div className="bot-cards">{filtered.filter(item=>item.category===group).map(item=><button type="button" key={item.id} className={`bot-card ${botId===item.id?'selected':''}`} aria-pressed={botId===item.id} aria-label={`Play ${item.name}, ${item.rating}${item.adaptive?', adaptive':''}`} title={`${item.name} (${item.referenceRating||item.rating})`} onClick={()=>chooseBot(item)}><BotAvatar bot={item}/><strong>{item.name}</strong><small>{item.referenceRating||item.rating}</small><Crowns count={progress?.bots?.[item.id]||0}/></button>)}</div>}
        </section>)}
        {!filtered.length&&<div className="no-bots"><strong>No opponents found</strong><p>Try a name, category, or rating.</p><button className="text-button" onClick={()=>setSearch('')}>Clear search</button></div>}
      </div>
    </>:<div className="engine-cards">{engines.map(item=><button type="button" key={item.id} className={`engine-card ${engineId===item.id?'selected':''}`} disabled={!item.available} onClick={()=>onChange({engineId:item.id})}><span><strong>{item.name}</strong><small>{item.available?(item.humanLike?'Human move model · ready':'Chess engine · ready'):item.reason||'Not installed'}</small></span><span className={`availability-dot ${item.available?'available':''}`}/></button>)}</div>}
    <details className="play-options"><summary>Game options <span>{color==='random'?'Random':color==='w'?'White':'Black'} · {timeControl.initialSeconds?`${timeControl.initialSeconds/60} + ${timeControl.incrementSeconds}`:'No timer'}</span></summary><div className="options-body">
      <label className="control-label">PLAY AS</label><div className="color-options">{['w','random','b'].map(value=><button type="button" className={color===value?'chosen':''} key={value} onClick={()=>onChange({color:value})}><span className={`color-swatch ${value}`}/>{value==='w'?'White':value==='b'?'Black':'Random'}</button>)}</div>
      <label className="control-label" htmlFor={`${id}-engine`}>OPPONENT ENGINE</label><select id={`${id}-engine`} value={engineId} onChange={e=>onChange({engineId:e.target.value})}>{!engineId&&<option value="">Select an installed engine</option>}{engines.map(item=><option key={item.id} value={item.id} disabled={!item.available}>{item.name}{item.available?'':' · unavailable'}</option>)}</select>
      <label className="rating-label" htmlFor={`${id}-rating`}>Target strength <output>{raw?`Level ${Math.max(1,engineRatings.indexOf(rating)+1)} · `:''}{rating}</output></label><input id={`${id}-rating`} aria-label="Target strength" type="range" min={raw?1:bot?.category==='New to Chess'?100:250} max={raw?25:3200} step={raw?1:25} value={raw?Math.max(1,engineRatings.indexOf(rating)+1):rating} onChange={e=>onChange({rating:raw?engineRatings[Number(e.target.value)-1]:Number(e.target.value)})}/><div className="rating-range"><span>{bot?.category==='New to Chess'?100:250}</span><span>3200</span></div>
      <label className="control-label">TIME CONTROL</label><div className="time-controls">{timeControls.map(([label,initialSeconds,incrementSeconds])=><button type="button" key={label} className={timeControl.initialSeconds===initialSeconds&&timeControl.incrementSeconds===incrementSeconds?'chosen':''} onClick={()=>onChange({timeControl:{initialSeconds,incrementSeconds}})}>{label}</button>)}</div>
      <fieldset className="assistance-options"><legend>Assistance</legend>{[['chat','Bot chat'],['evaluation','Evaluation bar'],['threats','Threat arrows'],['suggestions','Suggestion arrows'],['feedback','Move feedback'],['engine','Engine lines']].map(([key,label])=><label key={key}><span>{label}</span><input type="checkbox" checked={assistance[key]} onChange={e=>onChange({assistance:{...assistance,[key]:e.target.checked}})}/></label>)}</fieldset>
    </div></details>
    <button type="button" className="button primary start-button" disabled={disabled||!engine?.available||(!raw&&!bot)} onClick={onStart}>{busy?'Starting…':`Play ${raw?engine?.name||'engine':bot?.name||'bot'}`}<span aria-hidden="true">→</span></button>
    <details className="bot-disclosure"><summary>About ratings, bots & crowns</summary><p>Names, portraits, and reference ratings come from the public Chess.com roster. Unrated special bots start at a user-adjustable target of 1500. These are local simulations using {engine?.name||'your selected engine'}, not Chess.com’s proprietary bot behavior. Target ratings are uncalibrated. Maia predicts human moves; Stockfish novice styles use a local legal-move policy below 1100. Elsewhere style labels set chat context. Lc0 strength uses search limits.</p><p>Win without help for 3 crowns. Use 1–3 hints or undos for 2; more help, opening engine review during play, or enabled engine assistance earns 1. Bot chat does not reduce crowns.</p><a href="/bots/roster-provenance.json" target="_blank" rel="noreferrer">Portrait and rating sources</a></details>
  </div>;
}
