import React,{useEffect,useRef,useState} from 'react';

// Claude explains the engine evidence for one position. The server checks every cited move;
// when Claude is unavailable it answers with the deterministic engine summary instead.
const reasons={
 rate_limited:'You have reached this hour’s limit for AI explanations.',
 timeout:'The AI explanation took too long.',
 unverified_claims:'The AI answer mentioned moves outside the engine evidence, so it was withheld.',
 busy:'The AI coach is busy.',
 upstream_busy:'The AI coach is busy.',
 refusal:'The AI coach declined this request.',
 not_configured:'AI explanations are off on this server.',
 no_evidence:'There is no engine line to explain in this position.',
};
const escape=value=>value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
function MoveText({text,moves,notation}){
 if(!moves.length)return text;
 const pattern=new RegExp(`(${[...moves].sort((a,b)=>b.length-a.length).map(escape).join('|')})`,'g');
 return text.split(pattern).map((part,index)=>moves.includes(part)?<b key={index}>{notation(part)}</b>:part);
}
export default function CoachExplain({request,node,notation,model}){
 const [answers,setAnswers]=useState([]),[draft,setDraft]=useState(''),[pending,setPending]=useState(false);
 const controller=useRef(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 async function ask(question){
  if(controller.current)return;
  const abort=new AbortController(),id=crypto.randomUUID();controller.current=abort;setPending(true);
  setAnswers(current=>[...current,{id,question:question??null}]);
  const update=patch=>setAnswers(current=>current.map(item=>item.id===id?{...item,...patch}:item));
  try{
   const result=await request('/api/coach/explain',{...node,...(question?{question}:{})},abort.signal);
   update({result});if(question)setDraft('');
  }catch(error){if(error.name!=='AbortError')update({error:error.message});}
  finally{if(controller.current===abort){controller.current=null;setPending(false);}}
 }
 const explained=answers.some(item=>!item.question&&!item.error);
 return <section className="ai-coach" aria-label="AI explanation">
  <div className="ai-coach-heading"><span className="ai-badge">AI</span><strong>Ask the coach</strong><small>Claude explains the engine lines above. Moves it cites are checked against them.</small></div>
  {answers.map(item=><article className="ai-answer" key={item.id} aria-busy={!item.result&&!item.error}>
   {item.question&&<p className="ai-question">Why not {item.result?.question?notation(item.result.question):item.question}?</p>}
   {item.error?<p className="form-error" role="alert">{item.error}</p>:!item.result?<p className="ai-loading" role="status"><span className="thinking-dots"><i/><i/><i/></span>Reading the engine evidence…</p>:<>
    <p className="ai-text"><MoveText text={item.result.text} moves={item.result.citedMoves} notation={notation}/></p>
    <p className="ai-label">{item.result.source==='claude'?<>AI-generated by Claude{item.result.model||model?` (${item.result.model||model})`:''}. Grounded in {item.result.receipt.engine} · {item.result.receipt.movetimeMs} ms · depth {item.result.receipt.depth??'—'}. It can still be wrong; the engine lines are the evidence.</>:<>{reasons[item.result.fallbackReason]||'The AI coach is unavailable right now.'} Showing the verified engine summary.</>}</p>
   </>}
  </article>)}
  {!explained&&<button className="button secondary ai-explain" disabled={pending} onClick={()=>ask()}>Explain why</button>}
  <form className="ai-followup" onSubmit={event=>{event.preventDefault();if(draft.trim())ask(draft.trim());}}>
   <label htmlFor="ai-why-not">Why not</label>
   <input id="ai-why-not" autoComplete="off" maxLength={40} placeholder="a move, e.g. Nf3" value={draft} disabled={pending} onChange={event=>setDraft(event.target.value)}/>
   <button className="button secondary" disabled={pending||!draft.trim()}>Ask</button>
  </form>
 </section>;
}
