import React,{useEffect,useState} from 'react';
import Board from './Board.jsx';
import {replay} from './chess-state.js';

export default function EndgamePractice({request,user,settings,busy,onOpen,onGame,initialId,engines=[]}){
 const [items,setItems]=useState([]),[attempts,setAttempts]=useState([]),[selected,setSelected]=useState(initialId||'king-in-front');
 const [query,setQuery]=useState(''),[group,setGroup]=useState('All endings'),[orientation,setOrientation]=useState('w'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 useEffect(()=>{
  const controller=new AbortController();setLoading(true);setError('');setAttempts([]);
  Promise.all([request('/api/endgames',undefined,controller.signal),user?request('/api/endgame-attempts',undefined,controller.signal):Promise.resolve({attempts:[]})]).then(([catalog,history])=>{if(!controller.signal.aborted){setItems(catalog.items);setAttempts(history.attempts);}}).catch(error=>{if(error.name!=='AbortError')setError(error.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
  return()=>controller.abort();
 },[user?.id,retry]);
 const drill=items.find(item=>item.id===selected),board=replay([],drill?.fen),own=attempts.filter(a=>a.endgameId===selected);
 const visible=items.filter(item=>(group==='All endings'||item.group===group)&&`${item.title} ${item.note}`.toLowerCase().includes(query.toLowerCase()));
 const outcome=drill?.whiteOutcome===2?'White can win':drill?.whiteOutcome===-2?'Black can win':'Draw with best play';
 const result=attempt=>!attempt.result?'In progress':attempt.result==='1/2-1/2'?'Draw':attempt.result===(attempt.color==='w'?'1-0':'0-1')?'Won':'Lost';
 return <section className="endgame-page"><div className="opening-intro"><div><p className="eyebrow">MAKE THE LAST MOVES COUNT</p><h2>Finish with confidence.</h2><p>Convert an advantage. Defend a difficult position. Play it again.</p></div><span className="opening-local-count">{items.length||'…'}<small>original practice positions</small></span></div>
  {error&&<p className="form-error" role="alert">{error} <button className="text-button" onClick={()=>setRetry(n=>n+1)}>Reload endgames</button></p>}
  <div className="endgame-layout"><div className="endgame-preview"><div className="endgame-heading"><span className="eyebrow">{drill?.group||'ENDGAME PRACTICE'}</span><h3>{drill?.title||'Loading positions…'}</h3><p>{drill?`${board.turn()==='w'?'White':'Black'} to move · ${outcome}`:'Your local practice library'}</p></div>
   <Board chess={board} orientation={orientation} enabled={false} onSquare={()=>{}} onMove={()=>{}} settings={settings} label="Endgame preview board"/>
   <div className="endgame-board-actions"><button className="button small secondary" aria-label="Flip endgame board" onClick={()=>setOrientation(side=>side==='w'?'b':'w')}>Flip board</button><span>Play either side in setup</span></div>
   <div className="endgame-lesson"><p className="eyebrow">THE IDEA</p><p>{drill?.note}</p><div className="endgame-start"><button className="button primary" disabled={busy||loading||!drill} onClick={()=>onOpen(drill.id,true)}>Practice endgame <span aria-hidden="true">→</span></button><button className="button secondary" disabled={busy||loading||!drill} onClick={()=>onOpen(drill.id,false)}>Study endgame</button></div><small>Choose your opponent and strength. Attempts are saved on your local account.</small></div>
   <details className="endgame-evidence"><summary>Starting position & solved result</summary><p>{outcome}. This is the tablebase result from the displayed starting position with best play and a fresh fifty-move counter. Your chosen training opponent can make mistakes.</p><p>Local Syzygy tables cover all standard positions with 3–5 pieces and no castling rights. Later repetition and fifty-move state still matter. This is not a prediction of your game.</p><label htmlFor="endgame-fen">Starting FEN</label><input id="endgame-fen" readOnly value={drill?.fen||''} onFocus={e=>e.target.select()}/></details>
  </div><div className="endgame-catalogue"><div className="endgame-filters"><label className="sr-only" htmlFor="endgame-search">Search endgames</label><input id="endgame-search" type="search" placeholder="Search a skill or position" maxLength={100} value={query} onChange={e=>setQuery(e.target.value)}/><label className="sr-only" htmlFor="endgame-group">Endgame material</label><select id="endgame-group" value={group} onChange={e=>setGroup(e.target.value)}>{['All endings',...new Set(items.map(item=>item.group))].map(name=><option key={name}>{name}</option>)}</select></div><p className="section-label" role="status">{loading?'Loading…':`${visible.length} positions`}</p>
   <div className="endgame-results">{visible.map(item=>{const count=attempts.filter(a=>a.endgameId===item.id).length;return <button key={item.id} className={`endgame-card ${selected===item.id?'chosen':''}`} aria-label={`Choose ${item.title}`} aria-pressed={selected===item.id} onClick={()=>setSelected(item.id)}><span className="endgame-material" aria-hidden="true">{item.group==='Pawn endings'?'♟':item.group==='Rook endings'?'♜':item.group==='Queen endings'?'♛':'♞'}</span><span><small>{item.group}</small><strong>{item.title}</strong><small>{count?`${count} saved attempt${count===1?'':'s'}`:'Ready to practice'}</small></span><span aria-hidden="true">→</span></button>;})}{!loading&&!visible.length&&<div className="empty-state"><h3>No matching positions.</h3><p>Try a shorter search or another material group.</p></div>}</div>
   <section className="endgame-history" aria-label="Endgame attempts"><div className="section-label"><span>YOUR ATTEMPTS</span><span>{own.length}</span></div><h3>{drill?.title}</h3>{!user?<p>Sign in when you start to keep your attempts private on this Mac.</p>:!own.length?<p>Your first attempt starts here. You can return to it at any time.</p>:own.map(attempt=><button key={attempt.id} className="endgame-attempt" disabled={busy} aria-label={`${attempt.result?'Review':'Resume'} endgame attempt ${attempt.id}`} onClick={()=>onGame(attempt.id)}><span><strong>{result(attempt)} · {attempt.color==='w'?'White':'Black'}</strong><small>{attempt.engine==='Engine opponent'?(engines.find(e=>e.id===attempt.engineId)?.name||'Engine opponent'):attempt.engine} · target {attempt.rating} · {attempt.moves} half-move{attempt.moves===1?'':'s'}</small><small>{attempt.hints} hint{attempt.hints===1?'':'s'} · {attempt.undos} takeback{attempt.undos===1?'':'s'}{attempt.resultReason?` · ${attempt.resultReason}`:''}</small></span><span>{attempt.result?'Review':'Resume'} →</span></button>)}</section>
  </div></div></section>;
}
