import React,{useEffect,useRef,useState} from 'react';
import {Piece} from './Board.jsx';

export default function GameLibrary({api,user,games,busy,onOpen,onNew,onImport,onPosition,onAuth,Modal}){
 const [collections,setCollections]=useState([]),[active,setActive]=useState(''),[query,setQuery]=useState(''),[kind,setKind]=useState('all'),[sort,setSort]=useState('recent'),[collectionSort,setCollectionSort]=useState('recent');
 const [selected,setSelected]=useState([]),[target,setTarget]=useState(''),[editor,setEditor]=useState(null),[deleting,setDeleting]=useState(false),[working,setWorking]=useState(false),[loading,setLoading]=useState(!!user),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const alive=useRef(true),inFlight=useRef(false);
 useEffect(()=>{alive.current=true;const controller=new AbortController();if(user)api('/api/collections',undefined,controller.signal).then(data=>setCollections(data.collections)).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(alive.current)setLoading(false);});return()=>{alive.current=false;controller.abort();};},[]);
 const current=collections.find(c=>c.id===active),needle=query.trim().toLocaleLowerCase();
 const visible=games.filter(g=>(!current||current.gameIds.includes(g.id))&&(kind==='all'||(kind==='studies'?!!g.study?.branches?.length:g.source===kind))&&(!needle||[g.title,g.botName,g.engineId,g.opening?.name,g.opening?.eco,g.result].filter(Boolean).join(' ').toLocaleLowerCase().includes(needle))).sort((a,b)=>sort==='name'?a.title.localeCompare(b.title):sort==='oldest'?a.updatedAt.localeCompare(b.updatedAt):b.updatedAt.localeCompare(a.updatedAt));
 const ordered=[...collections].sort((a,b)=>collectionSort==='name'?a.name.localeCompare(b.name):b.updatedAt.localeCompare(a.updatedAt));
 const locked=working||busy,allSelected=visible.length>0&&visible.every(g=>selected.includes(g.id));
 function choose(id){setActive(id);setSelected([]);setQuery('');setKind('all');setNotice('');}
 async function change(path,body,after){
  if(inFlight.current)return;inFlight.current=true;setWorking(true);setError('');setNotice('');
  try{const data=await api(path,body);if(!alive.current)return;
   if(data.collection)setCollections(old=>[data.collection,...old.filter(c=>c.id!==data.collection.id)]);
   after(data);
  }catch(e){if(alive.current)setError(e.message);}
  finally{inFlight.current=false;if(alive.current)setWorking(false);}
 }
 async function refresh(){if(inFlight.current)return;inFlight.current=true;setWorking(true);setError('');try{const data=await api('/api/collections');if(alive.current){setCollections(data.collections);if(active&&!data.collections.some(c=>c.id===active))choose('');}}catch(e){if(alive.current)setError(e.message);}finally{inFlight.current=false;if(alive.current)setWorking(false);}}
 function save(event){event.preventDefault();const form=new FormData(event.currentTarget);change(editor.id?`/api/collections/${editor.id}`:'/api/collections',{name:form.get('name'),description:form.get('description'),...(editor.id?{revision:editor.revision}:{})},data=>{setEditor(null);choose(data.collection.id);setNotice(editor.id?'Collection updated.':'Collection created. Add games from All games.');});}
 function membership(collection,present){change(`/api/collections/${collection.id}/games`,{revision:collection.revision,gameIds:selected,present},()=>{setNotice(`${selected.length} ${selected.length===1?'game':'games'} ${present?'added to':'removed from'} ${collection.name}.`);setSelected([]);});}
 const filters=<div className="library-filters"><label className="library-search">Search games<input type="search" aria-label="Search saved games" placeholder="Title, opponent or opening…" value={query} onChange={e=>{setQuery(e.target.value);setSelected([]);}}/></label><label>Show<select aria-label="Game type" value={kind} onChange={e=>{setKind(e.target.value);setSelected([]);}}><option value="all">All types</option><option value="bot">Bot games</option><option value="import">Imported games</option><option value="studies">With variations</option></select></label><label>Sort<select aria-label="Sort saved games" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Recent first</option><option value="oldest">Oldest first</option><option value="name">Title A–Z</option></select></label></div>;
 return <section className="library-page organized-library">
  <div className="collection-heading"><div><span className="eyebrow">PICK UP WHERE YOU LEFT OFF</span><h2>Your chess, move by move.</h2><p>Keep the games you love. Return to the ideas that matter.</p></div><button className="button primary" onClick={onNew}>+ New game</button></div>
  {!user?<div className="empty-state"><h3>A place for your games.</h3><p>Sign in to save games, variations and collections on this server.</p><button className="button primary" onClick={onAuth}>Create an account</button></div>:<>
   <div className="library-summary"><span><strong>{games.length}</strong> saved {games.length===1?'game':'games'}</span><span><strong>{collections.length}</strong> {collections.length===1?'collection':'collections'}</span><span><strong>{games.reduce((n,g)=>n+(g.study?.branches?.length||0),0)}</strong> variations to explore</span></div>
   <div className="library-layout"><aside className="collection-sidebar" aria-label="Game collections"><div className="collection-sidebar-heading"><h3>Collections</h3><button className="text-button" disabled={locked||loading} onClick={()=>setEditor({name:'',description:''})}>+ New collection</button></div>
    <div className="desktop-collections"><button className={`collection-link ${!active?'active':''}`} aria-pressed={!active} onClick={()=>choose('')}><span>All games</span><small>{games.length}</small></button>
    <label className="collection-order">Sort collections<select aria-label="Sort collections" value={collectionSort} onChange={e=>setCollectionSort(e.target.value)}><option value="recent">Recently updated</option><option value="name">Name A–Z</option></select></label>
    {loading?<p role="status">Loading collections…</p>:ordered.map(c=><button key={c.id} className={`collection-link ${active===c.id?'active':''}`} aria-label={`Open collection ${c.name}`} aria-pressed={active===c.id} onClick={()=>choose(c.id)}><span>{c.name}</span><small>{c.gameIds.length}</small></button>)}
    {!loading&&!collections.length&&<p className="collection-tip">Opening ideas, memorable wins, lessons from a loss. Give your games a home.</p>}
    </div><label className="mobile-collection-picker">Open collection<select aria-label="Open saved collection" disabled={loading} value={active} onChange={e=>choose(e.target.value)}><option value="">{loading?'Loading collections…':`All games · ${games.length}`}</option>{ordered.map(c=><option key={c.id} value={c.id}>{c.name} · {c.gameIds.length}</option>)}</select></label>
    <p className="collection-private">Private to your local account</p>
   </aside><div className="library-content">
    <div className="library-content-heading"><div><span className="eyebrow">{current?'YOUR COLLECTION':'YOUR ARCHIVE'}</span><h3>{current?.name||'All games'}</h3>{current?.description&&<p>{current.description}</p>}</div>{current&&<div className="collection-actions"><button className="text-button" disabled={locked} onClick={()=>setEditor(current)}>Edit collection</button><button className="text-button" disabled={locked} onClick={()=>setDeleting(true)}>Delete collection</button></div>}</div>
    {error&&<div className="library-message" role="alert">{error} <button className="text-button" disabled={locked} onClick={refresh}>Refresh library</button></div>}{notice&&<p className="library-message" role="status">{notice}</p>}
    {filters}
    <div className="library-selection"><label><input type="checkbox" aria-label="Select all visible games" checked={allSelected} disabled={locked||!visible.length} onChange={()=>setSelected(allSelected?[]:visible.map(g=>g.id))}/>{selected.length?`${selected.length} selected`:`${visible.length} ${visible.length===1?'game':'games'}`}</label>{selected.length>0&&<div className="collection-bulk"><select aria-label="Add selected games to collection" value={target} disabled={locked} onChange={e=>setTarget(e.target.value)}><option value="">Choose collection</option>{ordered.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="button secondary" disabled={locked||!collections.some(c=>c.id===target)} onClick={()=>membership(collections.find(c=>c.id===target),true)}>Add selected</button>{current&&<button className="text-button" disabled={locked} onClick={()=>membership(current,false)}>Remove selected</button>}</div>}</div>
    {!visible.length?<div className="empty-state"><h3>{query||kind!=='all'?'No matching games.':current?'Ready for your first game.':'Your first game is waiting.'}</h3><p>{query||kind!=='all'?'Try another title, opponent or filter.':current?'Choose games from your archive and add them to this collection.':'Start a coach game, import a PGN or set up a position.'}</p>{current&&<button className="button secondary" onClick={()=>choose('')}>Browse all games</button>}</div>:<div className="games-grid">{visible.map(item=>{const count=Math.ceil((item.moves.length-(item.practice?.startPly||0))/2);return <article className="library-game" key={item.id}><label className="game-select"><input type="checkbox" aria-label={`Select game ${item.title}`} checked={selected.includes(item.id)} disabled={locked} onChange={e=>setSelected(old=>e.target.checked?[...old,item.id]:old.filter(id=>id!==item.id))}/></label><button className="game-card" onClick={()=>onOpen(item.id)} disabled={locked}><span className="game-card-icon"><Piece type={item.source==='import'?'b':'n'} color={item.color}/></span><span className="game-card-copy"><small>{item.practice?'POSITION PRACTICE':item.opening?`OPENING · ${item.opening.eco}`:item.positionSetup?'CUSTOM POSITION':item.source==='import'?'IMPORTED GAME':`${item.botName||item.engineId||'COACH'} · ${item.rating||`LEVEL ${item.level}`}`}</small><strong>{item.title}</strong><span>{count} {item.practice?'practice ':''}{count===1?'move':'moves'} · {item.result||'In progress'}{item.study?.branches?.length?` · ${item.study.branches.length} variations`:''}</span><time>{new Date(item.updatedAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</time></span><span aria-hidden="true">›</span></button></article>;})}</div>}
   </div></div>
  </>}
  <div className="library-footer"><button className="text-button" onClick={onImport}>Import a PGN</button><button className="text-button" disabled={locked} onClick={onPosition}>Set up position</button></div>
  {editor&&<Modal title={editor.id?'Edit collection':'New collection'} onClose={()=>{if(!working)setEditor(null);}}><form className="collection-form" onSubmit={save}><label>Collection name<input name="name" aria-label="Collection name" defaultValue={editor.name} required maxLength={80} autoFocus/></label><label>Description <small>(optional)</small><textarea name="description" aria-label="Collection description" defaultValue={editor.description} maxLength={1000} rows={3}/></label><p>Only your local account can access this collection.</p>{error&&<p role="alert">{error}</p>}<button className="button primary" disabled={working}>{working?'Saving…':editor.id?'Save collection':'Create collection'}</button></form></Modal>}
  {deleting&&current&&<Modal title="Delete collection?" onClose={()=>{if(!working)setDeleting(false);}}><p>Delete “{current.name}”? All games and variations stay in All games and your other collections.</p>{error&&<p role="alert">{error}</p>}<div className="collection-delete-actions"><button className="button secondary" disabled={working} onClick={()=>setDeleting(false)}>Keep collection</button><button className="button primary" disabled={working} onClick={()=>change(`/api/collections/${current.id}/delete`,{revision:current.revision},()=>{setCollections(old=>old.filter(c=>c.id!==current.id));setDeleting(false);choose('');setNotice('Collection deleted. All games and variations are preserved.');})}>Delete collection permanently</button></div></Modal>}
 </section>;
}
