import React,{useEffect,useRef,useState} from 'react';
import {Chess} from 'chess.js';
import Board,{Piece} from './Board.jsx';
import {replay,parseMove,moveRows} from './chess-state.js';

export default function LearningPath({request,user,settings,starterLessons,completed,onSignIn,onStarter,onProgress}){
 const [catalog,setCatalog]=useState({courses:[],lessons:[]}),[saved,setSaved]=useState({completed,sessions:[]}),[view,setView]=useState('path'),[query,setQuery]=useState(''),[level,setLevel]=useState(''),[topic,setTopic]=useState('');
 const [lessonId,setLessonId]=useState(null),[session,setSession]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[feedback,setFeedback]=useState(null),[typed,setTyped]=useState(''),[selected,setSelected]=useState(null),[promotion,setPromotion]=useState(null),[flipped,setFlipped]=useState(false);
 const owner=useRef(user?.id),selection=useRef(null);owner.current=user?.id;
 useEffect(()=>{const c=new AbortController();request('/api/curriculum',undefined,c.signal).then(setCatalog).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[]);
 useEffect(()=>{const c=new AbortController();setSaved({completed:user?completed:[],sessions:[]});setSession(null);setFeedback(null);setBusy(false);if(user){request('/api/lesson-progress',undefined,c.signal).then(setSaved).catch(e=>{if(e.name!=='AbortError')setError(e.message);});if(selection.current){const id=selection.current;request('/api/course-lessons/'+id+'/start',{},c.signal).then(data=>{if(selection.current===id)accept(data);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});}}return()=>c.abort();},[user?.id]);
 const lesson=catalog.lessons.find(l=>l.id===lessonId),course=catalog.courses.find(c=>c.id===lesson?.courseId),step=session?.step||0,challenge=lesson?.challenges[step],moves=session?.current.moves||[];
 const board=challenge?replay(moves,challenge.fen):new Chess(),side=challenge?new Chess(challenge.fen).turn():'w',enabled=session?.state==='active'&&session.current.state==='active'&&!busy;
 const done=new Set(saved.completed),active=saved.sessions.find(s=>s.state==='active'),next=catalog.lessons.find(l=>l.id===active?.lessonId)||catalog.lessons.find(l=>!done.has(l.id)),following=catalog.lessons.find(l=>l.id!==lessonId&&!done.has(l.id));
 useEffect(()=>{setTyped('');setSelected(null);setPromotion(null);},[lessonId,session?.id,session?.revision]);
 function accept(data){setSession(data.session);setSaved(data.progress);onProgress(data.progress.completed);}
 async function perform(action){if(busy)return;const id=user?.id,target=selection.current;setBusy(true);setError('');try{const data=await action();if(owner.current===id&&selection.current===target)return data;}catch(e){if(owner.current===id&&selection.current===target)setError(e.message);}finally{if(owner.current===id)setBusy(false);}}
 async function openLesson(id){selection.current=id;setLessonId(id);setSession(null);setFeedback(null);setError('');setFlipped(false);if(user){const data=await perform(()=>request('/api/course-lessons/'+id+'/start',{}));if(data)accept(data);}}
 function back(){selection.current=null;setLessonId(null);setSession(null);setFeedback(null);setError('');}
 async function act(action,move){const data=await perform(()=>request('/api/course-lessons/'+lessonId+'/action',{id:session.id,revision:session.revision,action,move}));if(data){accept(data);setFeedback(data);}}
 async function restart(){const data=await perform(()=>request('/api/course-lessons/'+lessonId+'/start',{restart:true}));if(data){accept(data);setFeedback(null);}}
 async function submit(value){if(!enabled)return;let move;try{move=parseMove(board,value);}catch{setError('That move is not legal here. Use the board, SAN or coordinates.');return;}await act('move',move);}
 function boardMove(from,to){if(!enabled||from===to)return;const choices=board.moves({square:from,verbose:true}).filter(m=>m.to===to);if(!choices.length){setSelected(null);setError('That move is not legal here.');return;}if(choices.some(m=>m.promotion)){setPromotion({from,to});return;}submit(from+to);}
 function square(value){if(!enabled)return;if(selected){if(selected===value){setSelected(null);return;}if(board.get(value)?.color===board.turn()){setSelected(value);return;}boardMove(selected,value);}else if(board.get(value)?.color===board.turn())setSelected(value);}
 const search=query.trim().toLowerCase();
 const lessons=catalog.lessons.filter(l=>{const c=catalog.courses.find(c=>c.id===l.courseId);return (!level||c.level===level)&&(!topic||l.topic===topic)&&(!search||`${l.title} ${l.description} ${l.topic} ${c.title} ${(l.keywords||[]).join(' ')} ${l.body.join(' ')}`.toLowerCase().includes(search));});
 const starters=starterLessons.filter(l=>(!level||level==='Starter')&&(!topic||l.category===topic)&&(!search||`${l.title} ${l.description} ${l.category} ${l.body.join(' ')}`.toLowerCase().includes(search)));
 return <section className="learning-path-page">
 {error&&<div className="feedback error" role="alert">{error}</div>}
 {lesson?<><div className="lesson-page-heading"><button className="text-button" disabled={busy} onClick={back}>← Learning path</button><span>{course?.level} · {course?.title}</span><h2>{lesson.title}</h2><p>{lesson.description}</p></div><div className="lesson-challenge-progress" aria-label="Lesson challenge progress">{lesson.challenges.map((c,i)=><span key={i} className={i<step||i===step&&session?.current.state==='solved'?'complete':i===step?'current':''}>{i<step||i===step&&session?.current.state==='solved'?'✓':i+1}<small>{c.title}</small></span>)}</div>
  <div className="training-layout"><div className="training-board-column"><div className="training-position-title"><span className="training-side"><Piece type="n" color={side}/>{session?.current.state==='solved'?'Challenge solved':`${side==='w'?'White':'Black'} to move`}</span><span>Challenge {step+1} of {lesson.challenges.length}</span></div><Board chess={board} orientation={flipped?(side==='w'?'b':'w'):side} enabled={!!enabled} selected={selected} onSquare={square} onMove={boardMove} settings={settings} lastMove={moves.at(-1)?.match(/.{1,2}/g)} label="Lesson challenge board"/>
  {promotion&&<div className="training-promotion" role="dialog" aria-label="Choose lesson promotion">{['q','r','b','n'].map(piece=><button key={piece} aria-label={`Promote to ${{q:'queen',r:'rook',b:'bishop',n:'knight'}[piece]}`} onClick={()=>submit(promotion.from+promotion.to+piece)}><Piece type={piece} color={board.turn()}/></button>)}<button onClick={()=>setPromotion(null)}>Cancel</button></div>}
  <div className="training-board-foot"><span>{session?.current.state==='solved'?'Challenge solved.':session?`${moves.length} half-moves saved`:'Explore the lesson, then sign in to save your practice.'}</span><button className="text-button" aria-label="Flip lesson board" onClick={()=>setFlipped(v=>!v)}>Flip board ⇄</button></div><form className="training-entry" onSubmit={e=>{e.preventDefault();submit(typed);}}><label className="sr-only" htmlFor="lesson-move">Lesson move</label><input id="lesson-move" placeholder="Your move, e.g. Nf3 or g1f3" value={typed} disabled={!enabled} onChange={e=>setTyped(e.target.value)}/><button className="button secondary" disabled={!enabled||!typed.trim()}>Play lesson move</button></form><div className="training-moves">{moveRows(moves,challenge.fen).map(row=><span key={row.ply}>{row.number}{row.color==='w'?'.':'…'} {row.san}</span>)}</div>{challenge.sourceUrl&&<p className="training-attribution">Position <a href={challenge.sourceUrl} target="_blank" rel="noreferrer">#{challenge.sourceId} · Lichess CC0</a> · source rating {challenge.sourceRating}. This exercise follows the recorded source continuation.</p>}</div>
  <aside className="training-panel course-lesson-panel"><p className="eyebrow">UNDERSTAND THE IDEA</p>{lesson.body.map((text,i)=><p key={i}>{text}</p>)}<div className="course-challenge-prompt"><span>{session?.current.state==='solved'?'CHALLENGE COMPLETE':'YOUR TURN'} · {step+1} / {lesson.challenges.length}</span><h3>{challenge.title}</h3><p>{challenge.prompt}</p></div>{feedback&&<div className={`learning-feedback ${feedback.correct===false?'incorrect':'correct'}`} role="status"><strong>{feedback.correct===false?'Try another move.':session.state==='complete'?'Lesson complete':session.current.state==='solved'?'Challenge solved':'Keep calculating.'}</strong><p>{feedback.message}</p></div>}{!feedback&&session?.current.state==='solved'&&<div className="learning-feedback correct" role="status"><strong>{session.state==='complete'?'Lesson complete':'Challenge solved'}</strong><p>{session.current.explanation}</p></div>}
  {!user?<button className="button primary full-width" onClick={onSignIn}>Sign in to save this lesson →</button>:!session?<button className="button primary full-width" disabled={busy} onClick={()=>openLesson(lesson.id)}>{busy?'Restoring lesson…':'Start challenges'}</button>:session.state==='complete'?<><div className="lesson-complete-banner"><span>✓</span><div><strong>Both challenges complete.</strong><p>Your progress is saved. Revisit this idea whenever you need it.</p></div></div>{following&&<button className="button primary full-width" disabled={busy} onClick={()=>openLesson(following.id)}>Next lesson →</button>}<div className="training-actions"><button className="button secondary" disabled={busy} onClick={restart}>Practice again</button><button className="text-button" disabled={busy} onClick={back}>Return to path</button></div></>:session.current.state==='solved'?<button className="button primary full-width" disabled={busy} onClick={()=>act('next')}>Continue to challenge {step+2} →</button>:<p className="lesson-save-note">{session.current.mistakes?`${session.current.mistakes} attempts to learn from. `:''}Correct moves are saved as you go. Both challenges are required for completion.</p>}
  </aside></div></>:<><div className="learning-path-hero"><div><p className="eyebrow">A LITTLE BETTER, EVERY DAY</p><h2>Build the habit.<br/>Understand the game.</h2><p>Follow a course, test the idea on the board, and pick up where you left off.</p></div><div className="learning-path-total"><strong>{catalog.lessons.filter(l=>done.has(l.id)).length}<span> / {catalog.lessons.length}</span></strong><span>guided lessons complete</span><small>24 board challenges · saved on this Mac</small></div></div>
  <div className="learning-view-tabs" role="group" aria-label="Learning views"><button aria-pressed={view==='path'} onClick={()=>setView('path')}>Learning path</button><button aria-pressed={view==='library'} onClick={()=>setView('library')}>Lesson library</button></div>
  {view==='path'?<>{next&&<div className="learning-next"><div><span>{active?'PICK UP WHERE YOU LEFT OFF':'YOUR NEXT STEP'}</span><h3>{next.title}</h3><p>{next.description}</p></div><button className="button primary" onClick={()=>openLesson(next.id)}>{active?'Continue lesson':'Start next lesson'} →</button></div>}<div className="course-path">{catalog.courses.map((c,index)=>{const units=catalog.lessons.filter(l=>l.courseId===c.id),count=units.filter(l=>done.has(l.id)).length;return <section key={c.id} className={`course-section ${c.color}`}><div className="course-header"><span className="course-number">{count===units.length?'✓':String(index+1).padStart(2,'0')}</span><div><p className="eyebrow">{c.level}</p><h3>{c.title}</h3><p>{c.description}</p></div><span className="course-count">{count} / {units.length} complete</span></div><div className="course-unit-list">{units.map((l,i)=><button key={l.id} aria-label={l.title} className={done.has(l.id)?'complete':''} onClick={()=>openLesson(l.id)}><span className="unit-marker">{done.has(l.id)?'✓':i+1}</span><div><strong>{l.title}</strong><p>{l.description}</p></div><span>{done.has(l.id)?'Review':saved.sessions.some(s=>s.lessonId===l.id)?'Continue':'2 challenges'} →</span></button>)}</div></section>;})}</div></>:<><div className="learning-library-filters"><label>Search lessons<input type="search" aria-label="Search lessons" placeholder="Try castling, a fork, or promotion" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Level<select aria-label="Lesson level" value={level} onChange={e=>setLevel(e.target.value)}><option value="">All levels</option>{catalog.courses.map(c=><option key={c.level}>{c.level}</option>)}<option>Starter</option></select></label><label>Topic<select aria-label="Lesson topic" value={topic} onChange={e=>setTopic(e.target.value)}><option value="">All topics</option>{[...new Set([...catalog.lessons.map(l=>l.topic),...starterLessons.map(l=>l.category)])].sort().map(t=><option key={t}>{t}</option>)}</select></label></div><p className="lesson-library-count">{lessons.length+starters.length} {lessons.length+starters.length===1?'lesson':'lessons'} found</p><div className="lesson-library-grid">{lessons.map(l=><button key={l.id} aria-label={l.title} onClick={()=>openLesson(l.id)}><span>{catalog.courses.find(c=>c.id===l.courseId)?.level} · {l.topic}</span><h3>{l.title}</h3><p>{l.description}</p><small>{done.has(l.id)?'✓ Completed':'2 board challenges'} →</small></button>)}</div>{!lessons.length&&!starters.length&&<div className="empty-state"><h3>No lessons match yet.</h3><p>Try another topic or clear the filters.</p></div>}</>}
  {(view==='path'||starters.length>0)&&<section className="starter-lesson-section"><div className="section-label"><span>STARTER LESSONS</span><span>YOUR ORIGINAL PROGRESS IS PRESERVED</span></div><div className="lesson-library-grid">{(view==='path'?starterLessons:starters).map(l=><button key={l.id} aria-label={l.title} onClick={()=>onStarter(l)}><span>{l.category}</span><h3>{l.title}</h3><p>{l.description}</p><small>{done.has(l.id)?'✓ Completed':'Read and answer'} →</small></button>)}</div></section>}
  <p className="training-attribution">Original ChessLab instruction with six attributed CC0 advanced positions. This local collection is growing; it does not reproduce the complete Chess.com lesson catalogue.</p>
 </>}
 </section>;
}
