import React,{useEffect,useState} from 'react';
import Board from './Board.jsx';
import {replay,moveRows,parseMove} from './chess-state.js';

const pieceNames={q:'queen',r:'rook',b:'bishop',n:'knight'};
export default function OpeningExplorer({request,settings,user,initialMoves=[],onStudy,busy:outerBusy}){
 const [expandedMoves,setExpandedMoves]=useState(false),[expandedGames,setExpandedGames]=useState(false);
 const [moves,setMoves]=useState(initialMoves),[ply,setPly]=useState(initialMoves.length),[source,setSource]=useState('elite'),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [orientation,setOrientation]=useState('w'),[selected,setSelected]=useState(null),[typed,setTyped]=useState(''),[promotion,setPromotion]=useState(null),[example,setExample]=useState(null),[examplePly,setExamplePly]=useState(0),[gameLoading,setGameLoading]=useState(false);
 const shownMoves=example?example.moves:moves,shownPly=example?examplePly:ply,board=replay(shownMoves.slice(0,shownPly)),fen=board.fen(),enabled=!example&&!outerBusy;
 useEffect(()=>{
  const controller=new AbortController();setLoading(true);setData(null);
  request('/api/explorer?'+new URLSearchParams({fen,source}),undefined,controller.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
  return()=>controller.abort();
 },[fen,source,user?.id]);
 useEffect(()=>{setSelected(null);setPromotion(null);setTyped('');setExpandedMoves(false);setExpandedGames(false);},[fen,example,source]);
 useEffect(()=>{if(!user&&source==='mine'){setSource('elite');setExample(null);}},[user]);
 function submit(input){try{const move=parseMove(board,input);setMoves([...moves.slice(0,ply),move]);setPly(ply+1);setError('');setSelected(null);setTyped('');setPromotion(null);}catch(e){setError(e.message);}}
 function boardMove(from,to){if(!enabled||from===to)return;const choices=board.moves({square:from,verbose:true}).filter(m=>m.to===to);if(!choices.length){setError(`${from}–${to} is not legal here.`);setSelected(null);return;}if(choices[0].promotion)setPromotion({from,to,choices:choices.map(m=>m.promotion)});else submit(from+to);}
 function square(at){if(!enabled)return;if(at===selected){setSelected(null);return;}if(selected&&board.get(at)?.color!==board.turn())boardMove(selected,at);else setSelected(board.get(at)?.color===board.turn()?at:null);}
 function jump(next){setError('');if(example)setExamplePly(next);else setPly(next);}
 async function showGame(id){setGameLoading(true);setError('');try{const result=await request('/api/explorer/games/'+id+'?'+new URLSearchParams({source}));setExample(result.game);setExamplePly(0);}catch(e){setError(e.message);}finally{setGameLoading(false);}}
 const rows=moveRows(shownMoves);
 return <section className="explorer"><div className="explorer-heading"><div><p className="eyebrow">LEARN FROM REAL GAMES</p><h2>{example?'Follow the whole game.':'Find the next move.'}</h2><p>{example?`${example.headers.White||'White'} — ${example.headers.Black||'Black'}`:'Explore a position. See what was played. Choose your own path.'}</p></div><label>Game database<select aria-label="Explorer database" value={source} disabled={gameLoading} onChange={e=>{setSource(e.target.value);setExample(null);setError('');}}><option value="elite">Lichess Elite · Nov 2025</option><option value="mine" disabled={!user}>My Games{!user?' · sign in':''}</option></select></label></div>
 {error&&<p className="form-error" role="alert">{error}</p>}
 <div className="explorer-layout"><div className="explorer-board-column"><div className="explorer-position-title"><strong>{board.turn()==='w'?'White':'Black'} to move</strong><span>{shownPly?`After ${rows[shownPly-1].number}${rows[shownPly-1].color==='w'?'.':'…'} ${rows[shownPly-1].san}`:'Starting position'}</span></div><Board chess={board} orientation={orientation} selected={selected} onSquare={square} onMove={boardMove} enabled={enabled} settings={settings} lastMove={shownPly?shownMoves[shownPly-1].match(/.{1,2}/g):null} label="Explorer board" positionKey={fen}/>
 {promotion&&<fieldset className="practice-promotion"><legend>Choose promotion</legend>{promotion.choices.map(piece=><button key={piece} aria-label={`Promote explorer pawn to ${pieceNames[piece]}`} onClick={()=>submit(promotion.from+promotion.to+piece)}>{pieceNames[piece]}</button>)}</fieldset>}
 <div className="opening-transport"><button className="button small secondary" aria-label="Explorer first position" disabled={!shownPly} onClick={()=>jump(0)}>First</button><button className="button small secondary" aria-label="Explorer previous move" disabled={!shownPly} onClick={()=>jump(shownPly-1)}>Previous</button><button className="button small secondary" aria-label="Explorer next move" disabled={shownPly===shownMoves.length} onClick={()=>jump(shownPly+1)}>Next</button><button className="button small secondary" aria-label="Explorer last position" disabled={shownPly===shownMoves.length} onClick={()=>jump(shownMoves.length)}>Last</button><button className="button small secondary" aria-label="Flip explorer board" onClick={()=>setOrientation(value=>value==='w'?'b':'w')}>Flip</button></div>
 <div className="opening-moves explorer-moves" aria-label="Explorer played moves">{rows.map(row=><button key={row.ply} aria-label={`Explorer move ${row.number}, ${row.color==='w'?'white':'black'}, ${row.san}`} aria-current={shownPly===row.ply?'step':undefined} onClick={()=>jump(row.ply)}>{row.number}{row.color==='w'?'.':'…'} {row.san}</button>)}</div>
 {example?<div className="explorer-example-actions"><button className="button primary" disabled={outerBusy} onClick={()=>onStudy(example.pgn)}>Study this example</button><button className="button secondary" onClick={()=>{setMoves(example.moves.slice(0,examplePly));setPly(examplePly);setExample(null);}}>Explore example position</button><button className="button secondary" onClick={()=>setExample(null)}>Return to exploration</button></div>:<form className="practice-move-entry" onSubmit={e=>{e.preventDefault();submit(typed);}}><label htmlFor="explorer-move">Explore a move</label><div><input id="explorer-move" aria-label="Explorer move" value={typed} onChange={e=>setTyped(e.target.value)} disabled={!enabled} autoComplete="off" placeholder="e4 or Nf3"/><button className="button primary" disabled={!enabled||!typed.trim()}>Explore move</button></div></form>}
 <details className="opening-details"><summary>Position details</summary><label htmlFor="explorer-fen">Current FEN</label><input id="explorer-fen" readOnly value={fen} onFocus={e=>e.target.select()}/></details></div>
 <div className="explorer-results"><div className="explorer-count" role="status"><strong>{loading?'…':data?.total.toLocaleString()||'0'}</strong><span>{data?.total===1?'game':'games'} from this position</span></div><div className="explorer-legend"><span><i className="result-white"/>White wins</span><span><i className="result-draw"/>Draws</span><span><i className="result-black"/>Black wins</span></div>
 <div className="explorer-table" aria-label="Explorer move statistics" aria-busy={loading}><div className="explorer-table-head"><span>MOVE</span><span>GAMES</span><span>RESULTS · WHITE / DRAW / BLACK</span></div>{data?.moves.slice(0,expandedMoves?undefined:8).map(row=><button className="explorer-row" key={row.move} aria-label={`Explore ${row.san}, ${row.total} games`} disabled={!!example||outerBusy} onClick={()=>submit(row.move)}><strong>{row.san}</strong><span>{row.total.toLocaleString()}</span><span className="explorer-bar" role="img" aria-label={`${row.white} White wins, ${row.draw} draws, ${row.black} Black wins`}><span className="result-white" style={{width:`${100*row.white/row.total}%`}} title={`${row.white} White wins`}>{row.white/row.total>=.12?`${Math.round(100*row.white/row.total)}%`:''}</span><span className="result-draw" style={{width:`${100*row.draw/row.total}%`}} title={`${row.draw} draws`}>{row.draw/row.total>=.12?`${Math.round(100*row.draw/row.total)}%`:''}</span><span className="result-black" style={{width:`${100*row.black/row.total}%`}} title={`${row.black} Black wins`}>{row.black/row.total>=.12?`${Math.round(100*row.black/row.total)}%`:''}</span></span></button>)}</div>
 {data?.moves.length>8&&<button className="explorer-expand" aria-expanded={expandedMoves} onClick={()=>setExpandedMoves(value=>!value)}>{expandedMoves?'Show 8 most played moves':`Show all ${data.moves.length} moves`}</button>}
 {!loading&&!data?.total&&<div className="empty-state"><h3>{data?.available?'No games here yet.':'Local game archive unavailable.'}</h3><p>{data?.available?(source==='mine'?'Complete or import a standard game to build your opening history.':'Try an earlier position or another line. This corpus indexes the first 30 moves.'):'Import the local archive using the instructions in the local workspace guide.'}</p></div>}
 {example&&<div className="explorer-example-info"><span className="eyebrow">EXAMPLE GAME</span><h3>{example.headers.White} — {example.headers.Black}</h3><p>{example.headers.WhiteElo||'Unrated'} / {example.headers.BlackElo||'Unrated'} · {example.headers.Date||'Date unknown'} · {example.result}</p><p>{example.headers.Event||'Saved game'}</p></div>}
 {!example&&data?.games.length>0&&<div className="explorer-examples"><h3>Example games</h3><p className="tiny-note">A sample of games that reached this position.</p>{data.games.slice(0,expandedGames?undefined:4).map(game=><button key={game.id} disabled={gameLoading} aria-label={`Replay ${game.headers.White} versus ${game.headers.Black}`} onClick={()=>showGame(game.id)}><span><strong>{game.headers.White||'White'} <small>{game.headers.WhiteElo||''}</small></strong><strong>{game.headers.Black||'Black'} <small>{game.headers.BlackElo||''}</small></strong></span><span>{game.result}<small>{game.headers.Date||''}</small></span><span aria-hidden="true">→</span></button>)}</div>}
 {!example&&data?.games.length>4&&<button className="explorer-expand" aria-expanded={expandedGames} onClick={()=>setExpandedGames(value=>!value)}>{expandedGames?'Show 4 example games':`Show all ${data.games.length} examples`}</button>}
 {data?.source&&<p className="explorer-source">{data.source.label} · {data.source.count.toLocaleString()} {data.source.count===1?'game':'games'}.<br/>{data.source.selection}.<br/>First 30 moves; each game counted once per position. Results describe this database, not the strength of a move.{source==='elite'&&<> <a href="https://database.nikonoel.fr/" target="_blank" rel="noreferrer">Source · CC0</a></>}</p>}</div></div></section>;
}
