import React,{useEffect,useRef,useState} from 'react';
import {Chess} from 'chess.js';
import Board,{Piece} from './Board.jsx';
import {replay,parseMove,moveRows} from './chess-state.js';

const modes={'3min':'3 minutes','5min':'5 minutes',survival:'Survival'};
const reasons={time:'Time’s up.',mistakes:'Three strikes. A fresh start awaits.',ended:'Run saved.',catalogue:'You reached the end of this difficulty range.'};
export default function PuzzleRush({request,user,settings,onSignIn,onBack,onPractice}){
 const [run,setRun]=useState(null),[variant,setVariant]=useState('3min'),[history,setHistory]=useState([]),[bests,setBests]=useState({'3min':0,'5min':0,survival:0});
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(Boolean(user)),[error,setError]=useState(''),[feedback,setFeedback]=useState(null),[typed,setTyped]=useState(''),[selected,setSelected]=useState(null),[promotion,setPromotion]=useState(null),[flipped,setFlipped]=useState(false),[clock,setClock]=useState(0);
 const owner=useRef(user?.id),latest=useRef(null),timing=useRef({serverNow:0,local:0});owner.current=user?.id;
 function accept(data){if(data.run?.id===latest.current?.id&&data.run.revision<latest.current.revision)return;latest.current=data.run;setRun(data.run);setHistory(data.history);setBests(data.bests);if(data.run)setVariant(data.run.variant);timing.current={serverNow:data.serverNow,local:performance.now()};setClock(data.serverNow);}
 useEffect(()=>{const c=new AbortController();latest.current=null;setRun(null);setHistory([]);setBests({'3min':0,'5min':0,survival:0});setBusy(false);setFeedback(null);setError('');setLoading(Boolean(user));if(user)request('/api/rush',undefined,c.signal).then(accept).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[user?.id]);
 const active=run?.state==='active',current=run?.current,moves=current?.moves||[],board=current?replay(moves,current.puzzle.fen):new Chess();
 const remaining=run?.deadline===null?null:Math.max(0,(run?.deadline||0)-clock),enabled=active&&!busy&&!loading&&(remaining===null||remaining>0);
 useEffect(()=>{setTyped('');setSelected(null);setPromotion(null);},[run?.id,run?.revision]);
 useEffect(()=>{
  if(!active||run.deadline===null)return;
  let cancelled=false,checked=false;const id=user?.id;
  const timer=setInterval(()=>{const time=timing.current.serverNow+performance.now()-timing.current.local;setClock(time);if(time>=run.deadline&&!checked){checked=true;request('/api/rush/'+run.id).then(data=>{if(!cancelled&&owner.current===id)accept(data);}).catch(e=>{if(!cancelled)setError(e.message+' Reload to recover the saved run.');});}},200);
  return()=>{cancelled=true;clearInterval(timer);};
 },[run?.id,run?.state,run?.deadline,user?.id]);
 async function perform(action){if(busy||loading)return;const id=user?.id;setBusy(true);setError('');try{const data=await action();if(owner.current===id)return data;}catch(e){if(owner.current===id)setError(e.message);}finally{if(owner.current===id)setBusy(false);}}
 async function start(){if(!user){onSignIn();return;}const data=await perform(()=>request('/api/rush/start',{variant}));if(data){accept(data);setFeedback(null);setFlipped(false);}}
 async function act(action,move){const data=await perform(()=>request(`/api/rush/${run.id}/action`,{action,move,revision:run.revision}));if(data){accept(data);setFeedback(data.message?{message:data.message,correct:data.correct}:null);}}
 async function submit(value){if(!enabled)return;let move;try{move=parseMove(board,value);}catch{setError('That move is not legal here. Use the board, SAN or coordinates.');return;}await act('move',move);}
 function boardMove(from,to){if(!enabled||from===to)return;const choices=board.moves({square:from,verbose:true}).filter(m=>m.to===to);if(!choices.length){setSelected(null);setError('That move is not legal here.');return;}if(choices.some(m=>m.promotion)){setPromotion({from,to});return;}submit(from+to);}
 function square(value){if(!enabled)return;if(selected){if(selected===value){setSelected(null);return;}if(board.get(value)?.color===board.turn()){setSelected(value);return;}boardMove(selected,value);}else if(board.get(value)?.color===board.turn()){setSelected(value);}}
 async function openRun(id){const data=await perform(()=>request('/api/rush/'+id));if(data){accept(data);setFeedback(null);}}
 async function retry(index){const data=await perform(()=>request(`/api/rush/${run.id}/retry`,{index}));if(data)onPractice(data.attempt);}
 const seconds=Math.ceil((remaining||0)/1000),timeLabel=remaining===null?'∞':`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;
 return <section className={`training-page rush-page ${active?'is-active':''}`}><div className="training-heading"><div><p className="eyebrow">PUZZLE RUSH · ON THIS MAC</p><h2>Find your rhythm.<br/>Beat your best.</h2><p>Harder puzzles. Three lives. One more idea.</p></div><button className="button secondary" onClick={onBack} disabled={active||busy}>Back to puzzles</button></div>
  {error&&<div className="inline-error" role="alert">{error}</div>}
  <div className="training-layout"><div className="training-board-column">{active&&<div className="rush-mobile-status" aria-label="Mobile Rush progress"><span><small>SOLVED</small><strong>{run.score}</strong></span><span><small>{run.deadline===null?'SURVIVAL':'TIME LEFT'}</small><strong role="timer" aria-label="Rush mobile time remaining">{timeLabel}</strong></span><span aria-label={`${3-run.mistakes} lives left`}><small>LIVES</small><strong className="rush-mobile-lives">{'♥'.repeat(3-run.mistakes)}{'×'.repeat(run.mistakes)}</strong></span></div>}<div className="training-position-title"><span className="training-side">{current?<><Piece type="k" color={current.puzzle.side}/>{current.puzzle.side==='w'?'White':'Black'} to solve</>:'Your first challenge awaits'}</span><span>{current?`#${current.puzzle.id} · source rating ${current.puzzle.rating}`:'Start easy. Build momentum.'}</span></div>
   <Board chess={board} orientation={flipped?(current?.puzzle.side==='b'?'w':'b'):(current?.puzzle.side||'w')} settings={settings} selected={selected} onSquare={square} onMove={boardMove} enabled={!!enabled} lastMove={(moves.at(-1)||current?.puzzle.trigger)?.match(/.{1,2}/g)} label="Rush puzzle board"/>
   {promotion&&<div className="training-promotion" role="dialog" aria-label="Choose Rush promotion">{['q','r','b','n'].map(piece=><button key={piece} aria-label={`Promote to ${{q:'queen',r:'rook',b:'bishop',n:'knight'}[piece]}`} onClick={()=>submit(promotion.from+promotion.to+piece)}><Piece type={piece} color={board.turn()}/></button>)}<button onClick={()=>setPromotion(null)}>Cancel</button></div>}
   <div className="training-board-foot"><span>{active?`Opponent played ${moves.length?moveRows(moves,current.puzzle.fen).at(-1)?.san:current.puzzle.triggerSan}. Your turn.`:run?'Run saved. Retry any puzzle below.':'Every full solution adds one point.'}</span><button className="text-button" aria-label="Flip Rush board" onClick={()=>setFlipped(v=>!v)}>Flip board ⇄</button></div>
   <form className="training-entry" onSubmit={e=>{e.preventDefault();submit(typed);}}><label className="sr-only" htmlFor="rush-move">Rush move</label><input id="rush-move" placeholder="Your move, e.g. Nf3 or g1f3" value={typed} disabled={!enabled} onChange={e=>setTyped(e.target.value)}/><button className="button secondary" disabled={!enabled||!typed.trim()}>Play Rush move</button></form>
  </div><aside className="training-panel rush-panel"><div className="training-tabs"><strong>{active?modes[run.variant]:'Choose your run'}</strong><span>Local best · {bests[variant]}</span></div>
   <div className="rush-scoreboard"><div><span>SOLVED</span><strong aria-label="Rush score">{run?.score||0}</strong></div><div><span>{run?.deadline===null?'SURVIVAL':'TIME LEFT'}</span><strong className={active&&remaining!==null&&remaining<15000?'rush-time-low':''} role="timer" aria-label="Rush time remaining">{run?timeLabel:variant==='survival'?'∞':variant==='5min'?'5:00':'3:00'}</strong></div></div>
   <div className="rush-lives" aria-label={`${3-(run?.mistakes||0)} Rush lives remaining`}>{[0,1,2].map(i=><span key={i} className={i<(run?.mistakes||0)?'lost':''} aria-hidden="true">{i<(run?.mistakes||0)?'×':'♥'}</span>)}<small>{run?.mistakes||0} of 3 mistakes</small></div>
   {active?<><p className="eyebrow">KEEP YOUR EYES ON THE BOARD</p><h2>{run.score?'Keep it going.':'You’ve got this.'}</h2><p>Finish the whole line for a point. One wrong move or skip uses a life.</p>{feedback&&<div className={`learning-feedback ${feedback.correct===false?'incorrect':'correct'}`} role="status">{feedback.message}</div>}<div className="training-actions"><button className="button secondary" disabled={busy} onClick={()=>act('skip')}>Skip · lose a life</button><button className="text-button" disabled={busy} onClick={()=>act('end')}>End run</button></div><p className="rush-note">{run.deadline===null?'Survival saves your place when you leave.':'The clock keeps running when you leave or reload.'} Hints and analysis unlock after the run.</p></>:<><p className="eyebrow">{run?'RUN COMPLETE':'FIND YOUR FLOW'}</p><h2>{run?reasons[run.reason]:'How far can you go?'}</h2><p>{run?`${run.score} solved · ${run.items.length} encountered. Your result is saved on this Mac.`:'Choose a sprint or take your time in Survival. Puzzles get harder as you go. Your puzzle rating stays unchanged.'}</p><div className="rush-variants" role="group" aria-label="Rush duration">{Object.entries(modes).map(([value,title])=><button key={value} aria-pressed={variant===value} disabled={busy||loading} onClick={()=>setVariant(value)}><strong>{title}</strong><small>{value==='survival'?'No clock':value==='3min'?'A quick sprint':'Find your pace'}</small></button>)}</div><button className="button primary full-width" disabled={busy||loading} onClick={start}>{loading?'Restoring your run…':!user?'Sign in to play Rush':run?'Play Rush again':'Start Rush'} →</button></>}
   <div className="rush-personal-bests" aria-label="Personal Rush bests">{Object.entries(modes).map(([key,title])=><div key={key}><strong>{bests[key]}</strong><span>{title} best</span></div>)}</div>
  </aside></div>
  {run?.items.length>0&&<section className="rush-results"><div className="section-label"><span>{active?'THIS RUN':'REVISIT THE IDEAS'}</span><span>{run.items.length} PUZZLES</span></div><div className="rush-result-grid">{run.items.map(item=><button key={item.index} disabled={active||busy} onClick={()=>retry(item.index)} aria-label={`Retry Rush puzzle ${item.index+1}, ${item.result}`}><span className={item.result==='solved'?'solved':'missed'}>{item.result==='solved'?'✓':item.result==='failed'?'×':'·'}</span><strong>{item.rating}</strong><small>#{item.puzzleId}</small></button>)}</div>{!active&&<p>Choose a puzzle to retry in Custom practice. Reveal its solution or open native analysis there.</p>}</section>}
  {history.length>0&&<section className="training-history"><div className="section-label"><span>YOUR RECENT RUNS</span><span>LAST 20</span></div><div className="rush-history-list">{history.map(item=><button key={item.id} disabled={active||busy} onClick={()=>openRun(item.id)} aria-label={`Open ${modes[item.variant]} Rush score ${item.score}`}><strong>{item.score}<small>solved</small></strong><span>{modes[item.variant]}<small>{new Date(item.endedAt).toLocaleString()}</small></span><span>{item.mistakes} / 3 mistakes<span aria-hidden="true"> ↗</span></span></button>)}</div></section>}
  <p className="training-attribution">Rush uses the local <a href="https://database.lichess.org/#puzzles" target="_blank" rel="noreferrer">Lichess CC0 puzzle collection</a>. Scores and bests belong to this account on this Mac.</p>
 </section>;
}
