import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Chess} from 'chess.js';
import Board,{Piece} from './Board.jsx';
import {parseMove,scoreText} from './chess-state.js';
const pieceNames={p:'pawn',n:'knight',b:'bishop',r:'rook',q:'queen',k:'king'};
export default function ReviewPractice({game,settings,side='both',request}){
 const [practice,setPractice]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[choice,setChoice]=useState(side),[staleRevision,setStaleRevision]=useState(undefined),[selected,setSelected]=useState(null),[typed,setTyped]=useState(''),[promotion,setPromotion]=useState(null),[flipped,setFlipped]=useState(false);
 const controller=useRef(null),alive=useRef(true),route=`/api/games/${game.id}/practice-review`;
 function install(value){setPractice(value);if(value)setChoice(value.side);setSelected(null);setTyped('');setPromotion(null);}
 async function load(){const abort=new AbortController();controller.current?.abort();controller.current=abort;setLoading(true);setError('');try{const data=await request(route,undefined,abort.signal);if(!abort.signal.aborted){install(data.practice);setStaleRevision(data.revision);}}catch(e){if(e.name!=='AbortError'&&alive.current)setError(e.message);}finally{if(alive.current&&!abort.signal.aborted)setLoading(false);if(controller.current===abort)controller.current=null;}}
 useEffect(()=>{alive.current=true;load();return()=>{alive.current=false;controller.current?.abort();};},[game.id]);
 async function act(type,move){if(controller.current)return;const abort=new AbortController();controller.current=abort;setBusy(true);setError('');try{const body=type==='start'?{side:choice,revision:practice?.revision??staleRevision}:{type,move,revision:practice.revision};const data=await request(route+(type==='start'?'/start':'/action'),body,abort.signal);if(!abort.signal.aborted)install(data.practice);}catch(e){if(e.name!=='AbortError'&&alive.current)setError(e.message);}finally{if(controller.current===abort)controller.current=null;if(alive.current)setBusy(false);}}
 const current=practice?.current,chess=useMemo(()=>new Chess(current?.fen),[current?.fen]),enabled=!!current&&current.outcome==='active'&&!current.feedback&&!busy&&!loading,orientation=flipped?(current?.color==='w'?'b':'w'):(current?.color||'w');
 function submit(value){if(!enabled)return;try{act('move',parseMove(chess,value));}catch{setError('Choose a legal move in this position.');}}
 function boardMove(from,to){if(!enabled)return;const possible=chess.moves({square:from,verbose:true}).filter(m=>m.to===to);if(!possible.length){setError('Choose a legal destination.');return;}if(possible.some(m=>m.promotion)){setPromotion({from,to,choices:possible.map(m=>m.promotion)});return;}submit(from+to);}
 function square(value){if(!enabled)return;const piece=chess.get(value);if(selected===value)setSelected(null);else if(selected&&piece?.color!==chess.turn())boardMove(selected,value);else setSelected(piece?.color===chess.turn()?value:null);}
 if(loading)return <p className="practice-loading" role="status">Opening your saved practice…</p>;
 const summary=practice?.summary;
 return <div className="review-practice" aria-label="Guided review practice">
  {error&&<div className="form-error" role="alert">{error} <button className="text-button" disabled={busy} onClick={load}>Reload saved practice</button></div>}
  {!practice||practice.complete?<div className="review-practice-summary"><span className="eyebrow">LEARN FROM YOUR GAME</span><h3>{practice?summary.total?'Every position revisited.':'No practice positions for this side.':'Find a stronger move.'}</h3><p>{practice?'Your original game, notes and variations are preserved.':'Retry the critical positions from this completed review, with the answer hidden until you ask for help.'}</p>{summary?.total>0&&<div className="practice-totals" aria-label="Practice results">{[['unassisted','First try, no hints'],['learned','Solved with practice'],['revealed','Revealed'],['skipped','Skipped']].map(([key,label])=><div key={key}><strong>{summary[key]}</strong><span>{label}</span></div>)}</div>}<label>Practice as<select aria-label="Practice side" value={choice} disabled={busy} onChange={e=>setChoice(e.target.value)}><option value="both">Both sides</option><option value="w">White</option><option value="b">Black</option></select></label><button className="button primary" disabled={busy} onClick={()=>act('start')}>{busy?'Preparing…':practice?'Start practice again':'Start practice'}</button>{practice&&<p className="tiny-note">Starting again replaces this practice run. Your source game stays intact.</p>}</div>:<>
   <div className="practice-heading"><div><span className="eyebrow">POSITION {practice.index+1} OF {summary.total}</span><h3>{current.feedback?(current.outcome==='revealed'?'The engine’s idea':'Your move, reviewed'):`${current.color==='w'?'White':'Black'} to move`}</h3><p>Original move: {current.number}{current.color==='w'?'.':'…'} {current.originalSan} · {current.classification}</p></div><button className="text-button" aria-label="Flip practice board" onClick={()=>setFlipped(!flipped)}>Flip board</button></div>
   <progress aria-label="Practice progress" value={summary.finished} max={summary.total}/>
   <div className="review-practice-grid"><div><Board chess={chess} orientation={orientation} selected={selected} enabled={enabled} onSquare={square} onMove={boardMove} settings={{...settings,arrows:true}} label="Review practice board" lastMove={current.lastMove} arrows={current.hint?.move&&!current.feedback?[current.hint.move]:[]} marks={current.hint&&!current.feedback?[{from:current.hint.square,to:current.hint.square,color:'Y'}]:[]}/>
    {promotion&&<fieldset className="practice-promotion"><legend>Choose promotion</legend>{promotion.choices.map(piece=><button key={piece} aria-label={`Promote practice pawn to ${pieceNames[piece]}`} onClick={()=>submit(promotion.from+promotion.to+piece)}><Piece type={piece} color={current.color}/><span>{pieceNames[piece]}</span></button>)}</fieldset>}
    <form className="practice-move-entry" onSubmit={e=>{e.preventDefault();submit(typed);}}><label htmlFor="practice-move">Your move</label><div><input id="practice-move" aria-label="Practice move" value={typed} onChange={e=>setTyped(e.target.value)} disabled={!enabled} placeholder="e4 or Nf3" autoComplete="off"/><button className="button primary" disabled={!enabled||!typed.trim()}>Try move</button></div></form></div>
    <div className="practice-coach" aria-live="polite"><span className="eyebrow">{busy?'CHECKING YOUR IDEA':current.outcome==='solved'?'FOUND IT':current.outcome==='revealed'?'RECOMMENDATION':current.outcome==='skipped'?'SKIPPED':'YOUR TURN'}</span><h3>{busy?'Looking at your move…':current.outcome==='solved'?'A stronger move.':current.outcome==='revealed'?'Study this recommendation.':current.outcome==='skipped'?'Continue when you are ready.':current.feedback?'Revisit your idea.':'What would you play here?'}</h3>
    {current.feedback&&<><p>{current.feedback.text}</p>{current.feedback.san&&<p>Your try: <strong>{current.feedback.san}</strong>{current.feedback.classification?` · ${current.feedback.classification}`:''}</p>}{current.feedback.explanation&&<p>{current.feedback.explanation}</p>}<p className="practice-engine-evidence">{current.feedback.engine} · {current.feedback.limits.movetime/1000}s per position<br/>{scoreText(current.feedback.score)} · White’s perspective. Search estimate.</p></>}
    {!current.feedback&&current.hint&&<p className="practice-hint">Look at the {pieceNames[current.hint.piece]} on <strong>{current.hint.square}</strong>. {current.hint.move?'The arrow shows the saved recommendation.':'Where could it help most?'}</p>}
    {!current.feedback&&current.outcome==='active'&&<p>Look for checks, captures and threats. Play your idea on the board or type it below.</p>}
    <div className="practice-actions">{current.outcome==='active'?<>{current.feedback&&<button className="button primary" disabled={busy} onClick={()=>act('retry')}>Try again</button>}<button className="button secondary" disabled={busy||current.hints>=2} onClick={()=>act('hint')}>{current.hints?'Show hint arrow':'Give me a hint'}</button><button className="text-button" disabled={busy} onClick={()=>act('reveal')}>Reveal recommendation</button><button className="text-button" disabled={busy} onClick={()=>act('skip')}>Skip position</button></>:<button className="button primary" disabled={busy} onClick={()=>act('next')}>{practice.index+1===summary.total?'See practice results':'Next practice position'}</button>}</div>
    <p className="tiny-note">{current.attempts} {current.attempts===1?'attempt':'attempts'} · {current.hints} {current.hints===1?'hint':'hints'}. Progress saves after each action.</p><p className="tiny-note">Alternatives use the local engine for up to two seconds per position. Your game and study remain unchanged.</p></div></div>
  </>}
 </div>;
}
