import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Chess} from 'chess.js';
import Board from './Board.jsx';
const modes={coordinates:'Coordinates',moves:'Moves',mixed:'Coordinates & Moves'},colors={w:'White',b:'Black',random:'White or Black'};
export default function VisionTraining({request,user,settings,onSignIn}){
 const [data,setData]=useState(null),[options,setOptions]=useState({mode:'coordinates',color:'w',coordinates:true}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[feedback,setFeedback]=useState(null),[selected,setSelected]=useState(null),[typed,setTyped]=useState(''),[stamp,setStamp]=useState(0);
 const clock=useRef({now:0,at:0}),lock=useRef(false),owner=useRef(user?.id),alive=useRef(true);owner.current=user?.id;
 function accept(next){clock.current={now:next.serverNow,at:performance.now()};setStamp(next.serverNow);setData(next);if(next.round)setOptions(({mode:next.round.mode,color:next.round.color,coordinates:next.round.coordinates}));}
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{const abort=new AbortController();lock.current=false;setData(null);setBusy(false);setError('');setFeedback(null);setSelected(null);setTyped('');if(user)request('/api/vision',undefined,abort.signal).then(accept).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[user?.id]);
 useEffect(()=>{const timer=setInterval(()=>setStamp(clock.current.now+performance.now()-clock.current.at),100);return()=>clearInterval(timer);},[]);
 async function send(path,body){if(lock.current)return;const identity=owner.current;lock.current=true;setBusy(true);setError('');try{const next=await request(path,body);if(alive.current&&owner.current===identity){accept(next);setFeedback(next.message?{correct:next.correct,text:next.message}:null);if(next.correct||body?.action==='quit'){setSelected(null);setTyped('');}}}catch(e){if(alive.current&&owner.current===identity)setError(e.message);}finally{if(alive.current&&owner.current===identity){lock.current=false;setBusy(false);}}}
 const r=data?.round,active=r?.state==='active',countdown=active&&stamp<r.startsAt,remaining=r?Math.max(0,Math.ceil((r.endsAt-stamp)/1000)):30,running=active&&!countdown&&remaining>0;
 useEffect(()=>{if(active&&remaining===0&&!busy&&!error)send('/api/vision');},[active,remaining,busy,error]);
 const prompt=active?r.prompt:null,board=useMemo(()=>{const b=new Chess();b.clear();if(prompt?.kind==='move')b.put({type:prompt.piece,color:r.orientation},prompt.from);return b;},[prompt,r?.orientation]);
 function answer(square,from){if(!running||lock.current)return;send('/api/vision/'+r.id,{action:'answer',revision:r.revision,square,...(from?{from}:{})});}
 function choose(square){if(!running||lock.current)return;if(prompt.kind==='square')answer(square);else if(square===prompt.from)setSelected(square);else if(selected===prompt.from)answer(square,selected);}
 function enter(event){event.preventDefault();if(!running||busy)return;const value=typed.trim();if(prompt.kind==='square'){if(!/^[a-h][1-8]$/.test(value)){setError('Enter a square such as e4.');return;}answer(value);return;}
  if(/^[a-h][1-8][a-h][1-8]$/.test(value)){answer(value.slice(2),value.slice(0,2));return;}
  const match=/^([KQRBN])([a-h][1-8])$/.exec(value);if(!match||match[1].toLowerCase()!==prompt.piece){setError('Enter notation for the displayed piece, such as '+prompt.text+'.');return;}answer(match[2],prompt.from);
 }
 const boardOptions={...settings,coordinates:active?r.coordinates:options.coordinates,animation:0,legalMoves:false,lastMove:false};
 const orientation=active?r.orientation:options.color==='b'?'b':'w';
 const best=data?.bests.find(b=>b.mode===options.mode&&b.color===options.color&&b.coordinates===options.coordinates);
 return <section className="vision-layout" aria-label="Vision training"><div className="vision-board-column"><div className="vision-board-heading"><strong>{orientation==='w'?'White':'Black'} perspective</strong><span>{active?modes[r.mode]:'30 seconds · Find your rhythm'}</span></div>{active&&<div className="vision-mobile-hud" aria-hidden="true"><strong>{countdown?Math.ceil((r.startsAt-stamp)/1000):prompt.text}</strong><span>{r.score} correct · 0:{String(countdown?30:remaining).padStart(2,'0')}</span></div>}<div className="vision-board-wrap"><Board chess={board} orientation={orientation} selected={selected} onSquare={choose} onMove={(from,to)=>answer(to,from)} enabled={running&&!busy} editing settings={boardOptions} label="Vision board"/>{(!active||countdown||remaining===0)&&<div className="vision-board-overlay"><span className="vision-target" aria-hidden="true">◎</span><strong>{countdown?Math.ceil((r.startsAt-stamp)/1000):active?'Time’s up':r?.state==='complete'?'Round complete':'See the square.'}</strong><p>{countdown?'Get ready':active?'Saving your result…':'Read the prompt. Trust your eyes.'}</p></div>}</div><p className="vision-instruction">{running?(prompt.kind==='square'?'Click or tap the named square.':'Select the piece, then its destination. You can also drag it.'):'Train your board awareness and reading of chess notation.'}</p></div>
 <div className="vision-panel"><p className="eyebrow">BOARD VISION</p><h2>{active?'Find it. Play it.':'Know every square.'}</h2><p className="vision-intro">A short exercise for reading the board, one square or move at a time.</p>
 {active&&<><div className="vision-prompt" aria-live="polite" aria-atomic="true"><small>{countdown?'GET READY':prompt.kind==='square'?'FIND THE SQUARE':'PLAY THE MOVE'}</small><strong aria-label="Vision prompt">{countdown?'…':prompt.text}</strong></div><div className="vision-metrics"><div><strong aria-label="Vision score">{r.score}</strong><span>Correct</span></div><div><strong aria-label="Vision mistakes">{r.mistakes}</strong><span>Misses</span></div><div className={remaining<=5?'vision-urgent':''}><strong role="timer" aria-label="Vision time remaining">0:{String(countdown?30:remaining).padStart(2,'0')}</strong><span>Remaining</span></div></div><form className="vision-entry" onSubmit={enter}><label htmlFor="vision-answer">Or type your answer</label><div><input id="vision-answer" autoComplete="off" autoCapitalize="off" value={typed} onChange={e=>setTyped(e.target.value)} disabled={!running||busy} placeholder={prompt.kind==='square'?'e4':'Qd3 or e2d3'}/><button className="button" disabled={!running||busy}>Answer</button></div></form></>}
 {!active&&r&&<div className="vision-result" role="status"><span>{r.state==='complete'?'Finished':'Ended early'}</span><strong>{r.score}<small> correct</small></strong><p>{r.mistakes} {r.mistakes===1?'miss':'misses'} · {modes[r.mode]} · {colors[r.color]}</p><p>{r.state==='complete'?'Saved to your local account.':'Excluded from personal bests.'}</p></div>}
 {feedback&&<p className={'vision-feedback '+(feedback.correct===false?'incorrect':'')} role="status">{feedback.text}</p>}
 {error&&<div role="alert" className="form-error"><p>{error}</p>{user&&<button className="button" disabled={busy} onClick={()=>send('/api/vision')}>Reload round</button>}</div>}
 <fieldset className="vision-options" disabled={active||busy}><legend>Round settings</legend><label>Training mode<select aria-label="Training mode" value={options.mode} onChange={e=>setOptions({...options,mode:e.target.value})}>{Object.entries(modes).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Board color<select aria-label="Board color" value={options.color} onChange={e=>setOptions({...options,color:e.target.value})}>{Object.entries(colors).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="vision-coordinate-toggle"><input type="checkbox" checked={options.coordinates} onChange={e=>setOptions({...options,coordinates:e.target.checked})}/>Show coordinates</label></fieldset>
 {active?<button className="text-button" disabled={busy} onClick={()=>send('/api/vision/'+r.id,{action:'quit',revision:r.revision})}>End round early</button>:<button className="button primary full-width" disabled={busy||!!user&&!data} onClick={()=>user?send('/api/vision/start',options):onSignIn()}>{!user?'Sign in to train':busy?'Starting…':r?'Start another round':'Start Vision'}</button>}
 <p className="vision-best">{best?'Personal best: '+best.score+' · '+best.rounds+' completed rounds':'No completed rounds for these settings yet.'}</p>
 </div>{!!data?.history.length&&<section className="vision-history" aria-label="Vision history"><h2>Recent rounds</h2><p>Only your scores, saved on this Mac. Bests compare the same mode, color choice and coordinate setting.</p><div className="vision-history-list">{data.history.map(item=><div key={item.id} className="vision-history-row"><span><strong>{modes[item.mode]}</strong><small>{colors[item.color]} · Coordinates {item.coordinates?'on':'off'}</small></span><span><strong>{item.score} correct</strong><small>{item.mistakes} misses · {item.state==='complete'?'Finished':item.state==='quit'?'Ended early':'In progress'}</small></span><time dateTime={new Date(item.startsAt).toISOString()}>{new Date(item.startsAt).toLocaleString()}</time></div>)}</div></section>}</section>;
}
